// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

#include <stdio.h>  // for sprintf(), printf()
#include "../CYD_MP3Player.h"

#define MP3_VOLUME_INI 6
#define MP3_PATH_ROOT "/MP3Player/"
#define MP3_PATH_LEVEL 2
#define MP3_PATH_CONFIG MP3_PATH_ROOT, MP3_PATH_LEVEL
#define PERIOD_TAKS1 1000 // [msec]
#define PERIOD_TAKS2 100  // [msec]

// https://embedded-kiddie.github.io/2024/07/22/
#define DO_EVERY(period, prev) \
static uint32_t prev = 0; for (uint32_t now = millis(); now - prev >= period; prev = now)

static CYD_MP3Player player;
static ID3Tags_t id3tags;

///////////////////// UI LOOP ////////////////////
UI_State_t ui_state;
UI_Option_t ui_option;
UI_Control_t ui_control;

///////////////////// VARIABLES ////////////////////
// SCREEN: ui_ScreenMain
lv_obj_t *ui_ScreenMain;
lv_obj_t *ui_ImageAlbum;
lv_obj_t *ui_ImageWave;
lv_obj_t *ui_MusicTitle;
lv_obj_t *ui_ElapsedStart;
lv_obj_t *ui_ElapsedEnd;
lv_obj_t *ui_ButtonPlay;
lv_obj_t *ui_ElapsedBar;
lv_obj_t *ui_Volume;

// SCREEN: ui_ScreenOption
lv_obj_t *ui_ScreenOption;
lv_obj_t *ui_BacklightRoller;
lv_obj_t *ui_SleepTimerRoller;
lv_obj_t *ui_FavoriteNewButton;
lv_obj_t *ui_FavoriteClearButton;

// SCREEN: ui_ScreenPlayList
lv_obj_t *ui_ScreenPlayList;
lv_obj_t *ui_ContainerPlayList;
lv_obj_t *ui_PlayListToMainUp;
lv_obj_t *ui_PlayListToMainDown;

// EVENTS

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
/*--------------------------------------------------------------------------------
 * Event handlers for Screen Main
 *--------------------------------------------------------------------------------*/
void ui_event_ScreenMain(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
    if (!ui_ScreenOption) {
      ui_ScreenOption_screen_init();
    }
    lv_indev_wait_release(lv_indev_active());
    lv_screen_load_anim(ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, false);
  }

  else if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
    if (!ui_ContainerPlayList) {
      ui_ScreenPlayList_screen_init(); // initialize ui_ScreenPlayList and ui_ContainerPlayList
    }
    lv_obj_set_align  (ui_ContainerPlayList,  LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag   (ui_PlayListToMainUp,   LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_PlayListToMainDown, LV_OBJ_FLAG_HIDDEN);

    ui_list_focus_playing(player.GetPlayNo());
    lv_indev_wait_release(lv_indev_active());
    lv_screen_load_anim(ui_ScreenPlayList, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, false);
  }

  else if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
    if (!ui_ContainerPlayList) {
      ui_ScreenPlayList_screen_init(); // initialize ui_ScreenPlayList and ui_ContainerPlayList
    }
    lv_obj_set_align  (ui_ContainerPlayList,  LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_PlayListToMainUp,   LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag   (ui_PlayListToMainDown, LV_OBJ_FLAG_HIDDEN);

    ui_list_focus_playing(player.GetPlayNo());
    lv_indev_wait_release(lv_indev_active());
    lv_screen_load_anim(ui_ScreenPlayList, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, false);
  }
#if false
  else if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenPlayList, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenPlayList_screen_init);
  }
#endif
}

void ui_event_MenuDotMain(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenOption_screen_init);
  }
}

void ui_event_Favorite(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    lv_obj_t *obj = lv_event_get_target_obj(e);
    ui_option.favorite = lv_obj_get_state(obj) & LV_STATE_CHECKED;
    printf("ui_option.favorite: %d\n", ui_option.favorite);
  }
}

void ui_event_Repeat(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    lv_obj_t *obj = lv_event_get_target_obj(e);
    ui_option.repeat = lv_obj_get_state(obj) & LV_STATE_CHECKED;
    printf("ui_option.repeat: %d\n", ui_option.repeat);
  }
}

void ui_event_Shuffle(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    lv_obj_t *obj = lv_event_get_target_obj(e);
    ui_option.shuffle = lv_obj_get_state(obj) & LV_STATE_CHECKED;
    printf("ui_option.shuffle: %d\n", ui_option.shuffle);
  }
}

void ui_event_ButtonPlay(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    lv_state_t state = lv_obj_get_state(ui_ButtonPlay);
    ui_state = state & LV_STATE_CHECKED ? UI_STATE_RESUME : UI_STATE_PAUSE;
  }
}

void ui_event_ButtonNext(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    ui_state = UI_STATE_NEXT;
  }
}

void ui_event_ButtonPrev(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    ui_state = UI_STATE_PREV;
  }
}

void ui_event_VolumeMax(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    int vol = lv_slider_get_value(ui_Volume) + 1;
    vol = constrain(vol, MP3_VOLUME_MIN, MP3_VOLUME_MAX);
    lv_slider_set_value(ui_Volume, vol, LV_ANIM_OFF);
    player.SetVolume(vol);
  }
}

void ui_event_VolumeMin(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    int vol = lv_slider_get_value(ui_Volume) - 1;
    vol = constrain(vol, MP3_VOLUME_MIN, MP3_VOLUME_MAX);
    lv_slider_set_value(ui_Volume, vol, LV_ANIM_OFF);
    player.SetVolume(vol);
  }
}

void ui_event_Volume(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_VALUE_CHANGED) {
    int vol = lv_slider_get_value(ui_Volume);
    player.SetVolume(vol);
  }
}

void ui_event_ElapsedBar(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_VALUE_CHANGED) {
    if (player.IsPlaying()) {
      uint32_t elapsed = lv_slider_get_value(ui_ElapsedBar);
      audioSetElapsedTime(elapsed);
    }
  }
}

/*--------------------------------------------------------------------------------
 * Event handlers for Screen Option
 *--------------------------------------------------------------------------------*/
void ui_event_ScreenOption(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenMain_screen_init);
  }
}

void ui_event_OptionToMainRight(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenMain_screen_init);
  }
}

void ui_event_FavoriteSwitch( lv_event_t * e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if ( event_code == LV_EVENT_VALUE_CHANGED) {
    (e);
    _ui_state_modify(ui_FavoriteClearButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
  }
}

void ui_event_FavoriteDropdown(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_VALUE_CHANGED) {
    (e);
  }
}

void ui_event_BacklightSwitch(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_state_modify(ui_BacklightRoller, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
    lv_obj_t *obj = lv_event_get_target_obj(e);
    ui_option.backlight = lv_obj_get_state(obj) & LV_STATE_CHECKED;
    printf("ui_option.backlight: %d\n", ui_option.backlight);
  }
}

void ui_event_SleepTimerSwitch(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_state_modify(ui_SleepTimerRoller, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
    lv_obj_t *obj = lv_event_get_target_obj(e);
    ui_option.sleepTimer = lv_obj_get_state(obj) & LV_STATE_CHECKED;
    printf("ui_option.sleepTimer: %d\n", ui_option.sleepTimer);
  }
}

/*--------------------------------------------------------------------------------
 * Event handlers for Screen Playlist
 *--------------------------------------------------------------------------------*/
void ui_event_PlayListToMainUp(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScreenMain_screen_init);
  }
}

void ui_event_PlayListToMainDown(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScreenMain_screen_init);
  }
}
#if false
void ui_event_MenuBackToLeft(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenMain_screen_init);
  }
}

void ui_event_MenuBluetoothOn(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenOption_screen_init);
  }
}

void ui_event_MenuBluetoothOff(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenOption_screen_init);
  }
}
#endif
/////////////////// LOCAL FUNCTIONS //////////////////
static const char* sec_to_str(uint32_t sec) {
  static char str[8];
  snprintf(str, sizeof(str)-1, "%2d:%02d", sec / 60, sec - (sec / 60) * 60);
  str[sizeof(str)-1] = '\0';
  return (const char*)str;
}

static void update_epalsed_time(void) {
  uint32_t duration = audioGetDuration();
  uint32_t elapsed  = audioGetElapsedTime();
  if (duration < elapsed) {
    duration = elapsed;
  }
  lv_slider_set_range(ui_ElapsedBar, 0, duration);
  lv_slider_set_value(ui_ElapsedBar, elapsed, LV_ANIM_OFF);
  lv_label_set_text(ui_ElapsedStart, sec_to_str(elapsed));
  lv_label_set_text(ui_ElapsedEnd,   sec_to_str(duration));
}

/*--------------------------------------------------------------------------------
 * Control next or previous play / stop or continuous play
 *--------------------------------------------------------------------------------*/
static void ui_control_play(bool next) {
  if (ui_ScreenPlayList) {
    ui_list_update_cell(ui_control.focusNo, false);
    ui_list_update_icon(ui_control.playNo,  false);
  }

  if (next) {
    player.PlayNext();
  } else {
    player.PlayPrev();
  }

  // update ui_control and look of the play button
  ui_control.playNo = ui_control.focusNo = player.GetPlayNo();
  lv_obj_set_state(ui_ButtonPlay, LV_STATE_CHECKED, true);

  if (ui_ScreenPlayList) {
    ui_list_update_play(ui_control.playNo, true);
  }
}

///////////////////// SCREENS ////////////////////
void ui_init(void) {
  ui_ScreenMain_screen_init();
  lv_disp_load_scr(ui_ScreenMain);

  ui_control.sleepTimer = 30 * 1000;
  ui_state = UI_STATE_INIT;

  audioInit();
}

////////////////// GLOBAL FUNCTIONS /////////////////
bool ui_loop(void) {
  switch (ui_state) {
    case UI_STATE_INIT:
      player.begin(MP3_PATH_ROOT);
      player.SetVolume(MP3_VOLUME_INI);
      lv_slider_set_value(ui_Volume, MP3_VOLUME_INI, LV_ANIM_OFF);
      // no break
    case UI_STATE_START:
      player.ScanFileList(MP3_PATH_LEVEL);
      player.SortFileList(true);
      if (player.GetCounts()) {
        ui_set_playNo(0);
        ui_state = UI_STATE_PLAY;
      } else {
        ui_state = UI_STATE_IDLE;
      }
      break;
    case UI_STATE_PLAY:
      player.AutoPlay();
      break;
    case UI_STATE_STOP:
      lv_obj_set_state(ui_ButtonPlay, LV_STATE_CHECKED, false);
      // no break
    case UI_STATE_PAUSE:
      player.PauseResume();
      ui_state = UI_STATE_IDLE;
      break;
    case UI_STATE_RESUME:
      player.PauseResume();
      ui_state = UI_STATE_PLAY;
      break;
    case UI_STATE_NEXT:
      ui_control_play(true);
      ui_state = UI_STATE_PLAY;
      break;
    case UI_STATE_PREV:
      ui_control_play(false);
      ui_state = UI_STATE_PLAY;
      break;
    case UI_STATE_ID3DATA:
      lv_label_set_text_fmt(ui_MusicTitle, "%s %s / %s / %s",
        LV_SYMBOL_AUDIO,
        id3tags.title.c_str(),
        id3tags.artist.c_str(),
        id3tags.album.c_str()
      );
      ui_state = UI_STATE_PLAY;
      break;
    case UI_STATE_IDLE:
    default:
      break;
  }

  // Periodical task
  DO_EVERY(PERIOD_TAKS1, task1Time) {
    if (player.IsPlaying()) {
      update_epalsed_time();
    }
  }

  DO_EVERY(PERIOD_TAKS2, task2Time) {
    if (player.IsPlaying()) {
      // Serial.printf("%d\n", audioGetRMS() & 0xffff);
    }
  }

  // Backlight control according to the duration of non-operation
  if (ui_control.sleepTimer > lv_disp_get_inactive_time(NULL)) {
    return true;  // keep backlight on
  } else {
    return false; // turn backlight off
  }
}

/*--------------------------------------------------------------------------------
 * Redraw the display panel when waking up from sleep
 *--------------------------------------------------------------------------------*/
void ui_redisplay(void) {
  lv_disp_trig_activity(NULL);
  lv_disp_load_scr(lv_scr_act());
}

/*--------------------------------------------------------------------------------
 * Start to play with the specified track
 *--------------------------------------------------------------------------------*/
void ui_set_playNo(uint32_t track_id) {
  // start the specified track to play
  player.SetPlayNo(track_id);

  // update ui_control
  ui_control.playNo = ui_control.focusNo = track_id;

  // update the look of the play button
  if (ui_state != UI_STATE_PLAY) {
    lv_obj_set_state(ui_ButtonPlay, LV_STATE_CHECKED, true);
    ui_state = UI_STATE_PLAY;
  }
}

/*--------------------------------------------------------------------------------
 * Get the latest information on MP3Player
 *--------------------------------------------------------------------------------*/
uint32_t ui_get_playNo(void) {
  return player.GetPlayNo();
}

uint32_t ui_get_counts(void) {
  return player.GetCounts();
}

/*--------------------------------------------------------------------------------
 * Get ID3 tags (title, album, artist) from the file specified by id
 *--------------------------------------------------------------------------------*/
void ui_get_id3tags(uint32_t track_id, ID3Tags_t &tags) {
  player.GetID3Tags(track_id, tags);
}

/*--------------------------------------------------------------------------------
 * Optional functions for audio-I2S (defined in CYD_Audio.h as a weak function)
 * Note: These functions will be executed in the context of CORE 1.
 *--------------------------------------------------------------------------------*/
void audio_id3data(const char *info) {
  // Avoid a race condition with ui_state set by audio_eof_mp3()
  if (ui_state == UI_STATE_PLAY) {
    char *p;
    if (p = strstr(info, "Title: ")) {
      id3tags.title = p + 7;
    } else
    if (p = strstr(info, "Artist: ")) {
      id3tags.artist = p + 8;
    } else
    if (p = strstr(info, "Album: ")) {
      id3tags.album = p + 7;
      ui_state = UI_STATE_ID3DATA;
    }
  }
}

void audio_eof_mp3(const char *info) {
  if (!player.IsLastSong() || ui_option.repeat) {
    ui_state = UI_STATE_NEXT;
  } else {
    ui_state = UI_STATE_STOP;
  }
}