// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// UI LOOP ////////////////////

#include <stdio.h>  // for printf()
#include "../CYD_MP3Player.h"

CYD_MP3Player player;

#define MP3_VOLUME_INI 8
#define MP3_PATH_ROOT "/MP3Player/"
#define MP3_PATH_CONFIG MP3_PATH_ROOT, 2

// defined in LVGL_Arduino_MP3Player.ino
extern void DisplaySleep(void);
extern void DisplayWakeup(void);
extern bool IsDisplayAwake(void);

typedef enum {
  UI_STATE_INIT,
  UI_STATE_IDLE,
  UI_STATE_PAUSE,
  UI_STATE_RESUME,
  UI_STATE_NEXT,
  UI_STATE_PREV,
  UI_STATE_PLAY,
  UI_STATE_STOP,
  UI_STATE_SLEEP,
  UI_STATE_WAKEUP,
} UI_State_t;

/*
 * Audio-Length:
 * BitsPerSample:
 * BitRate:
 */
UI_State_t ui_state;
UI_Option_t ui_option;
UI_Control_t ui_control;

void ui_loop(void) {
  if (IsDisplayAwake() && ui_control.sleepTimer <= lv_disp_get_inactive_time(NULL)) {
    DisplaySleep();
  }

  switch (ui_state) {
    case UI_STATE_PLAY:
      player.AutoPlay();
      break;
    case UI_STATE_RESUME:
      player.PauseResume();
      ui_state = UI_STATE_PLAY;
      break;
    case UI_STATE_PAUSE:
      player.PauseResume();
      ui_state = UI_STATE_IDLE;
      break;
    case UI_STATE_NEXT:
      player.PlayNext();
      lv_obj_set_state(ui_ButtonPlay, LV_STATE_CHECKED, true);
      ui_state = UI_STATE_PLAY;
      break;
    case UI_STATE_PREV:
      player.PlayPrev();
      lv_obj_set_state(ui_ButtonPlay, LV_STATE_CHECKED, true);
      ui_state = UI_STATE_PLAY;
      break;
    case UI_STATE_STOP:
      player.StopPlay();
      ui_state = UI_STATE_IDLE;
      break;
    case UI_STATE_INIT:
      player.begin();
      player.ScanFileList(MP3_PATH_CONFIG);
      player.SortFileList(true);
      player.SetVolume(MP3_VOLUME_INI);
      player.SetPlayNo(ui_control.playNo);
      lv_slider_set_value(ui_Volume, MP3_VOLUME_INI, LV_ANIM_OFF);
      ui_state = UI_STATE_IDLE;

      // start playing: it makes ui_state to UI_STATE_RESUME
      lv_obj_set_state(ui_ButtonPlay, LV_STATE_CHECKED, true);
      lv_obj_send_event(ui_ButtonPlay, LV_EVENT_CLICKED, NULL);
      break;
    case UI_STATE_IDLE:
    default:
      break;
  }
}

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
lv_obj_t *ui_ScreenMain;  void ui_event_ScreenMain  (lv_event_t *e);
lv_obj_t *ui_MenuDotMain; void ui_event_MenuDotMain (lv_event_t *e);
lv_obj_t *ui_Favourite;   void ui_event_Favourite   (lv_event_t *e);
lv_obj_t *ui_Repeat;      void ui_event_Repeat      (lv_event_t *e);
lv_obj_t *ui_Shuffle;     void ui_event_Shuffle     (lv_event_t *e);
lv_obj_t *ui_ButtonPlay;  void ui_event_ButtonPlay  (lv_event_t *e);
lv_obj_t *ui_ButtonNext;  void ui_event_ButtonNext  (lv_event_t *e);
lv_obj_t *ui_ButtonPrev;  void ui_event_ButtonPrev  (lv_event_t *e);
lv_obj_t *ui_VolumeMax;   void ui_event_VolumeMax   (lv_event_t *e);
lv_obj_t *ui_VolumeMin;   void ui_event_VolumeMin   (lv_event_t *e);
lv_obj_t *ui_Volume;      void ui_event_Volume      (lv_event_t *e);
lv_obj_t *ui_ElapsedBar;  void ui_event_ElapsedBar  (lv_event_t *e);
lv_obj_t *ui_ImageAlbum;
lv_obj_t *ui_ImageWave;
lv_obj_t *ui_MusicTitle;
lv_obj_t *ui_ElapsedStart;
lv_obj_t *ui_ElapsedEnd;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenOption
void ui_ScreenOption_screen_init(void);
lv_obj_t *ui_ScreenOption;      void ui_event_ScreenOption    (lv_event_t *e);
lv_obj_t *ui_MenuBackRight;     void ui_event_MenuBackRight   (lv_event_t *e);
lv_obj_t *ui_FavoriteDropdown;  void ui_event_FavoriteDropdown(lv_event_t *e);
lv_obj_t *ui_BacklightSwitch;   void ui_event_BacklightSwitch (lv_event_t *e);
lv_obj_t *ui_SleepTimerSwitch;  void ui_event_SleepTimerSwitch(lv_event_t *e);
lv_obj_t *ui_FavoriteSwitch;    void ui_event_FavoriteSwitch  (lv_event_t *e);
lv_obj_t *ui_FavoriteLabel;
lv_obj_t *ui_FavoriteNewLabel;
lv_obj_t *ui_FavoriteClearLabel;
lv_obj_t *ui_FavoriteNewButton;
lv_obj_t *ui_FavoriteClearButton;
lv_obj_t *ui_BacklightLabel;
lv_obj_t *ui_BacklightRoller;
lv_obj_t *ui_SleepTimerLabel;
lv_obj_t *ui_SleepTimerRoller;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPlayList
void ui_ScreenPlayList_screen_init(void);
lv_obj_t *ui_ScreenPlayList;    void ui_event_ScreenPlayList  (lv_event_t *e);
lv_obj_t *ui_MenuBackLeft;      void ui_event_MenuBackLeft    (lv_event_t *e);
lv_obj_t *ui_MenuBackUp;        void ui_event_MenuBackUp      (lv_event_t *e);
lv_obj_t *ui_MenuBackDown;      void ui_event_MenuBackDown    (lv_event_t *e);
#if false
lv_obj_t *ui_CheckFavorite;     void ui_event_CheckFavorite   (lv_event_t *e);
lv_obj_t *ui_MenuBluetoothOn;   void ui_event_MenuBluetoothOn (lv_event_t *e);
lv_obj_t *ui_MenuBluetoothOff;  void ui_event_MenuBluetoothOff(lv_event_t *e);
#endif
lv_obj_t *ui_ContainerPlayList;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenMain(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenOption_screen_init);
  }
  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenPlayList, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScreenPlayList_screen_init);
  }
  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenPlayList, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScreenPlayList_screen_init);
  }
#if false
  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenPlayList, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenPlayList_screen_init);
  }
#endif
}

void ui_event_MenuDotMain(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenOption_screen_init);
  }
}

void ui_event_Favourite(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    (e);
  }
}

void ui_event_Repeat(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    (e);
  }
}

void ui_event_Shuffle(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    (e);
  }
}

void ui_event_ButtonPlay(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    lv_state_t state = lv_obj_get_state(ui_ButtonPlay);

    if (state & LV_STATE_CHECKED) {
      ui_state = UI_STATE_RESUME;
    } else { // LV_STATE_DEFAULT
      ui_state = UI_STATE_PAUSE;
    }
  }
}

void ui_event_ButtonNext(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    ui_state = UI_STATE_NEXT;
  }
}

void ui_event_ButtonPrev(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    ui_state = UI_STATE_PREV;
  }
}

void ui_event_VolumeMax(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    int vol = lv_slider_get_value(ui_Volume) + 1;
    vol = constrain(vol, MP3_VOLUME_MIN, MP3_VOLUME_MAX);
    lv_slider_set_value(ui_Volume, vol, LV_ANIM_OFF);
    player.SetVolume(vol);
  }
}

void ui_event_VolumeMin(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    int vol = lv_slider_get_value(ui_Volume) - 1;
    vol = constrain(vol, MP3_VOLUME_MIN, MP3_VOLUME_MAX);
    lv_slider_set_value(ui_Volume, vol, LV_ANIM_OFF);
    player.SetVolume(vol);
  }
}

void ui_event_Volume(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_VALUE_CHANGED) {
    int vol = lv_slider_get_value(ui_Volume);
    player.SetVolume(vol);
  }
  if (event_code == LV_EVENT_PRESSED) {
    (e);
  }
  if (event_code == LV_EVENT_RELEASED) {
    (e);
  }
}

void ui_event_ElapsedBar(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_VALUE_CHANGED) {
    (e);
  }
}

void ui_event_ScreenOption(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenMain_screen_init);
  }
}

void ui_event_MenuBackRight(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenMain_screen_init);
  }
}

void ui_event_FavoriteSwitch( lv_event_t * e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if ( event_code == LV_EVENT_VALUE_CHANGED) {
    (e);
    _ui_state_modify(ui_FavoriteClearButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
  }
}

void ui_event_FavoriteDropdown(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_VALUE_CHANGED) {
    (e);
  }
}

void ui_event_BacklightSwitch(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_state_modify(ui_BacklightRoller, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
    (e);
  }
}

void ui_event_SleepTimerSwitch(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_state_modify(ui_SleepTimerRoller, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
    (e);
  }
}

void ui_event_ScreenPlayList(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScreenMain_screen_init);
  }
  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScreenMain_screen_init);
  }
}

void ui_event_MenuBackLeft(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenMain_screen_init);
  }
}
#if false
void ui_event_MenuBluetoothOn(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenOption_screen_init);
  }
}

void ui_event_MenuBluetoothOff(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenOption_screen_init);
  }
}

void ui_event_CheckFavorite(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    (e);
  }
}
#endif
void ui_event_MenuBackUp(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    (e);
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScreenMain_screen_init);
  }
}

void ui_event_MenuBackDown(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    (e);
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScreenMain_screen_init);
  }
}

///////////////////// SCREENS ////////////////////

void ui_init(void) {
  ui_ScreenMain_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(ui_ScreenMain);

  ui_state = UI_STATE_INIT;
  ui_control.sleepTimer = 15 * 1000;

  audioInit();
}