// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include <stdio.h>  // for sprintf(), printf()

#include "../CYD_MP3Player.h"
static CYD_MP3Player player;

#define MP3_PATH_ROOT "/MP3Player/"
#define MP3_PATH_LEVEL 2
#define MP3_PATH_CONFIG MP3_PATH_ROOT, MP3_PATH_LEVEL
#define PERIOD_TAKS1 1000 // [msec]
#define PERIOD_TAKS2 100  // [msec]

// https://embedded-kiddie.github.io/2024/07/22/
#define DO_EVERY(period, prev) \
static uint32_t prev = 0; for (uint32_t now = millis(); now - prev >= period; prev = now)

static bool saveID3tags;
static ID3Tags_t id3tags;
static UI_State_t nextState;

///////////////////// UI LOOP ////////////////////
UI_State_t ui_state;
UI_Option_t ui_option;
UI_Control_t ui_control;

///////////////////// VARIABLES ////////////////////
// SCREEN: ui_ScreenMain
lv_obj_t *ui_ScreenMain;
lv_obj_t *ui_ImageAlbum;
lv_obj_t *ui_ImageWave;
lv_obj_t *ui_MusicTitle;
lv_obj_t *ui_ElapsedStart;
lv_obj_t *ui_ElapsedEnd;
lv_obj_t *ui_ButtonPlay;
lv_obj_t *ui_ElapsedBar;
lv_obj_t *ui_Volume;

// SCREEN: ui_ScreenOption
lv_obj_t *ui_ScreenOption;
lv_obj_t *ui_BacklightRoller;
lv_obj_t *ui_SleepTimerRoller;
lv_obj_t *ui_FavoriteNewButton;
lv_obj_t *ui_FavoriteClearButton;

// SCREEN: ui_ScreenPlayList
lv_obj_t *ui_ScreenPlayList;
lv_obj_t *ui_ContainerPlayList;
lv_obj_t *ui_PlayListToMainUp;
lv_obj_t *ui_PlayListToMainDown;

// EVENTS

// IMAGES AND IMAGE SETS
#include "_pictures.h"

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
/*--------------------------------------------------------------------------------
 * Event handlers for Screen Main
 *--------------------------------------------------------------------------------*/
void ui_event_ScreenMain(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenOption_screen_init);
  }

  else if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
    if (!ui_ContainerPlayList) {
      ui_ScreenPlayList_screen_init(); // initialize ui_ScreenPlayList and ui_ContainerPlayList
    }

    lv_obj_set_align  (ui_ContainerPlayList,  LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag   (ui_PlayListToMainUp,   LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_PlayListToMainDown, LV_OBJ_FLAG_HIDDEN);

    ui_list_focus_playing(player.GetPlayNo());
    lv_indev_wait_release(lv_indev_active());
    lv_screen_load_anim(ui_ScreenPlayList, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, false);
  }

  else if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
    if (!ui_ContainerPlayList) {
      ui_ScreenPlayList_screen_init(); // initialize ui_ScreenPlayList and ui_ContainerPlayList
    }

    lv_obj_set_align  (ui_ContainerPlayList,  LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_PlayListToMainUp,   LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag   (ui_PlayListToMainDown, LV_OBJ_FLAG_HIDDEN);

    ui_list_focus_playing(player.GetPlayNo());
    lv_indev_wait_release(lv_indev_active());
    lv_screen_load_anim(ui_ScreenPlayList, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, false);
  }
#if false
  else if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenPlayList, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenPlayList_screen_init);
  }
#endif
}

void ui_event_MenuDotMain(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenOption_screen_init);
  }
}

void ui_event_Favorite(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    lv_obj_t *obj = lv_event_get_target_obj(e);
    ui_option.favorite = lv_obj_get_state(obj) & LV_STATE_CHECKED;
  }
}

void ui_event_Repeat(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    lv_obj_t *obj = lv_event_get_target_obj(e);
    ui_option.repeat = (uint8_t)(lv_obj_get_state(obj) & LV_STATE_CHECKED ? 1 : 0);
  }
}

void ui_event_Shuffle(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    lv_obj_t *obj = lv_event_get_target_obj(e);
    ui_option.shuffle = (lv_obj_get_state(obj) & LV_STATE_CHECKED ? true : false);
  }
}

void ui_event_ButtonPlay(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    lv_state_t state = lv_obj_get_state(ui_ButtonPlay);
    ui_state = state & LV_STATE_CHECKED ? UI_STATE_RESUME : UI_STATE_PAUSE;
  }
}

void ui_event_ButtonNext(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    ui_state = UI_STATE_NEXT;
    bitSet(ui_option.repeat, 7); // force to set the bit temporarily
  }
}

void ui_event_ButtonPrev(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    ui_state = UI_STATE_PREV;
    bitSet(ui_option.repeat, 7); // force to set the bit temporarily
  }
}

void ui_event_VolumeMax(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    int vol = lv_slider_get_value(ui_Volume) + 1;
    vol = constrain(vol, MP3_VOLUME_MIN, MP3_VOLUME_MAX);
    lv_slider_set_value(ui_Volume, vol, LV_ANIM_OFF);
    player.SetVolume(vol);
  }
}

void ui_event_VolumeMin(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    int vol = lv_slider_get_value(ui_Volume) - 1;
    vol = constrain(vol, MP3_VOLUME_MIN, MP3_VOLUME_MAX);
    lv_slider_set_value(ui_Volume, vol, LV_ANIM_OFF);
    player.SetVolume(vol);
  }
}

void ui_event_Volume(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_VALUE_CHANGED) {
    int vol = lv_slider_get_value(ui_Volume);
    player.SetVolume(vol);
  }
}

void ui_event_ElapsedBar(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_VALUE_CHANGED) {
    if (player.IsPlaying()) {
      uint32_t elapsed = lv_slider_get_value(ui_ElapsedBar);
      audioSetElapsedTime(elapsed);
    }
  }
}

/*--------------------------------------------------------------------------------
 * Event handlers for Screen Option
 *--------------------------------------------------------------------------------*/
void ui_event_ScreenOption(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenMain_screen_init);
  }
}

void ui_event_OptionToMainRight(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenMain_screen_init);
  }
}

void ui_event_FavoriteSwitch(lv_event_t * e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if ( event_code == LV_EVENT_VALUE_CHANGED) {
    (e);
    _ui_state_modify(ui_FavoriteClearButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
  }
}

void ui_event_FavoriteDropdown(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_VALUE_CHANGED) {
    (e);
  }
}

void ui_event_BacklightSwitch(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_state_modify(ui_BacklightRoller, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);

    lv_obj_t *obj = lv_event_get_target_obj(e);
    ui_option.backlight = lv_obj_get_state(obj) & LV_STATE_CHECKED;
  }
}

void ui_event_SleepTimerSwitch(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_state_modify(ui_SleepTimerRoller, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);

    lv_obj_t *obj = lv_event_get_target_obj(e);
    ui_option.sleepTimer = lv_obj_get_state(obj) & LV_STATE_CHECKED;
  }
}

/*--------------------------------------------------------------------------------
 * Event handlers for Screen Playlist
 *--------------------------------------------------------------------------------*/
void ui_event_PlayList_Heart(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    MetaData_t meta;
    uint32_t track_id = (uint32_t)lv_event_get_user_data(e);
    player.GetMetaData(track_id, &meta);

    lv_obj_t *obj = (lv_obj_t*)lv_event_get_current_target(e);
    meta.selected = lv_obj_get_state(obj) & LV_STATE_CHECKED;

    // prevent input while saving metadata to SD card
    lv_indev_enable(NULL, false);
    bool saved = player.PutMetaData(track_id, &meta);
    lv_indev_enable(NULL, true);

    // in case the metadata file cannot be saved, save it separately
    if (!saved) {
      saveID3tags = true;
    }
  }
}

void ui_event_PlayListToMainUp(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScreenMain_screen_init);
  }
}

void ui_event_PlayListToMainDown(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScreenMain_screen_init);
  }
}
#if false
void ui_event_MenuBackToLeft(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenMain_screen_init);
  }
}

void ui_event_MenuBluetoothOn(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenOption_screen_init);
  }
}

void ui_event_MenuBluetoothOff(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenOption_screen_init);
  }
}
#endif
/////////////////// LOCAL FUNCTIONS //////////////////
static void update_epalsed_time(void) {
  uint32_t duration = audioGetDuration();
  uint32_t elapsed  = audioGetElapsedTime();

  if (duration < elapsed) {
    duration = elapsed;
  }

  if (duration) {
    id3tags.meta.duration = duration;
  }

  lv_slider_set_range(ui_ElapsedBar, 0, duration);
  lv_slider_set_value(ui_ElapsedBar, elapsed, LV_ANIM_OFF);

  char time[8];
  lv_snprintf(time, sizeof(time), "%" LV_PRIu32 ":%02" LV_PRIu32, elapsed  / 60, elapsed  % 60);
  lv_label_set_text(ui_ElapsedStart, time);

  lv_snprintf(time, sizeof(time), "%" LV_PRIu32 ":%02" LV_PRIu32, duration / 60, duration % 60);
  lv_label_set_text(ui_ElapsedEnd,   time);
}

/*--------------------------------------------------------------------------------
 * Check and update the metadata when playback finishes
 *--------------------------------------------------------------------------------*/
static void update_metadata(void) {
  // prevent input while saving metadata to SD card
  lv_indev_enable(NULL, false);

  if (player.IsPlaying()) {
    player.PauseResume();
  }

  // update favorite
  if (saveID3tags) {
    if (player.UpdateMetaData()) {
      saveID3tags = false;
    }
  }

  // update duration
  MetaData_t meta;
  uint32_t playNo = player.GetPlayNo();
  player.GetMetaData(playNo, &meta);
  if (meta.duration < id3tags.meta.duration) {
    meta.duration = id3tags.meta.duration;
    player.PutMetaData(playNo, &meta);
    ui_list_update_duration(playNo, meta.duration);
  }

  if (!player.IsPlaying()) {
    player.PauseResume();
  }

  lv_indev_enable(NULL, true);
}

/*--------------------------------------------------------------------------------
 * Show the picture for album
 *--------------------------------------------------------------------------------*/
static void display_picture(uint32_t playNo) {
  char buf[FS_BUF_SIZE], *ptr;

#if PICTURE_ON_SD
  buf[0] = MY_FS_ARDUINO_SD_LETTER;
  buf[1] = ':';
  player.GetFilePath(playNo, buf + 2, sizeof(buf) - 2);

  if (ptr = strrchr(buf, '.')) {
    strcpy(ptr + 1, PICTURE_EXT);
    if (FS_DEV.exists(buf + 2)) {
      lv_gif_set_src(ui_ImageAlbum, buf);
      return;
    }
  }

  if (ptr = strrchr(buf, '/')) {
    strcpy(ptr + 1, "@picture." PICTURE_EXT);
    if (FS_DEV.exists(buf + 2)) {
      lv_gif_set_src(ui_ImageAlbum, buf);
      return;
    }
  }
#else
  player.GetFilePath(playNo, buf, sizeof(buf));

  if (ptr = strrchr(buf, '/')) {
    strcpy(ptr + 1, PICTURE_FILE);

    if (FS_DEV.exists(buf)) {
      FS_FILE file = FS_DEV.open(buf, FILE_READ);

      if (file) {
        int i = -1;
#ifdef  SDFATFS_USED
        String n = "";
        while (file.available()) {
          n += file.readString();
        }
        file.close();
        if (isdigit(n[0])) {
          i = atoi(n.c_str());
        }
#else // SD
        file.read((uint8_t*)buf, sizeof(buf));
        file.close();
        buf[sizeof(buf) - 1] = '\0';
        if (isdigit(buf[0])) {
          i = atoi(buf);
        }
#endif // SdFat or SD
        if (0 <= i && i < N_PICTURES) {
          lv_image_set_src(ui_ImageAlbum, pictures[i]);
          return;
        }
      }
    }
  }
#endif

  lv_image_set_src(ui_ImageAlbum, &ui_img_album_png);
}

/*--------------------------------------------------------------------------------
 * Control next/previous play or stop/continuous play
 *--------------------------------------------------------------------------------*/
static bool play_next(bool next) {
  if (ui_ScreenPlayList) {
    ui_list_update_cell(ui_control.focusNo, false);
    ui_list_update_icon(ui_control.playNo,  false);
  }

  bool ret = true;
  if (ui_option.favorite) {
    ret = player.NextSelected(next, (ui_option.repeat ? true : false));
  } else {
    if (next) {
      player.PlayNext();
    } else {
      player.PlayPrev();
    }
  }

  bitClear(ui_option.repeat, 7); // clear the bit that has been temporarily forced set

  ui_control.playNo = ui_control.focusNo = player.GetPlayNo();
  display_picture(ui_control.playNo);

  // update ui_control and look of the play button
  lv_obj_set_state(ui_ButtonPlay, LV_STATE_CHECKED, true);

  if (ui_ScreenPlayList) {
    ui_list_update_play(ui_control.playNo, true);
  }

  return ret;
}

/*--------------------------------------------------------------------------------
 * Check out the favorite playlists
 *--------------------------------------------------------------------------------*/
static bool check_favorite(void) {
  return !ui_option.favorite || player.IsPlaying() || player.IsSelected();
}

///////////////////// SCREENS ////////////////////
void ui_init(void) {
  ui_ScreenMain_screen_init();
  lv_disp_load_scr(ui_ScreenMain);

  ui_control.sleepTimer = 30 * 1000;
  ui_state = UI_STATE_INIT;

  audioInit();
}

////////////////// GLOBAL FUNCTIONS /////////////////
bool ui_loop(void) {
  switch (ui_state) {
    case UI_STATE_INIT:
      if (player.begin(MP3_PATH_ROOT, MP3_VOLUME_INI)) {
        lv_slider_set_value(ui_Volume, MP3_VOLUME_INI, LV_ANIM_OFF);
        ui_state = UI_STATE_START;
      } else {
        ui_state = UI_STATE_ERROR;
      }
      break;
    case UI_STATE_START:
      if (player.ScanFileList(MP3_PATH_LEVEL /* , ui_option.shuffle */)) {
        ui_set_playNo(0);
        ui_state = UI_STATE_PLAY;
      } else {
        ui_state = UI_STATE_ERROR;
      }
      break;
    case UI_STATE_PLAY:
      if (!check_favorite()) {
        ui_state = UI_STATE_NEXT;
      } else if (!player.AutoPlay()) {
        ui_state = UI_STATE_ERROR;
      }
      break;
    case UI_STATE_STOP:
      lv_obj_set_state(ui_ButtonPlay, LV_STATE_CHECKED, false);
      // no break
    case UI_STATE_PAUSE:
      player.PauseResume();
      ui_state = UI_STATE_IDLE;
      break;
    case UI_STATE_RESUME:
      player.PauseResume();
      ui_state = UI_STATE_PLAY;
      break;
    case UI_STATE_NEXT:
      if (play_next(true)) {
        ui_state = UI_STATE_PLAY;
      } else {
        ui_state = UI_STATE_STOP;
      }
      break;
    case UI_STATE_PREV:
      if (play_next(false)) {
        ui_state = UI_STATE_PLAY;
      } else {
        ui_state = UI_STATE_STOP;
      }
      break;
    case UI_STATE_ID3:
      lv_label_set_text_fmt(ui_MusicTitle, "%s %s / %s / %s",
        LV_SYMBOL_AUDIO,
        id3tags.title.c_str(),
        id3tags.artist.c_str(),
        id3tags.album.c_str()
      );
      ui_state = UI_STATE_PLAY;
      break;
    case UI_STATE_EOF:
      update_metadata();
      ui_state = nextState;
      break;
    case UI_STATE_ERROR:
      lv_label_set_text_fmt(ui_MusicTitle, "%s %s", LV_SYMBOL_WARNING, player.GetError());
      ui_state = UI_STATE_IDLE;
    case UI_STATE_IDLE:
    default:
      break;
  }

  // Periodical task
  DO_EVERY(PERIOD_TAKS1, task1Time) {
    if (player.IsPlaying()) {
      update_epalsed_time();
    }
  }

  DO_EVERY(PERIOD_TAKS2, task2Time) {
    if (player.IsPlaying()) {
      // Serial.printf("%d\n", audioGetRMS() & 0xffff);
    }
  }

  // Backlight control according to the duration of non-operation
  if (ui_control.sleepTimer > lv_disp_get_inactive_time(NULL)) {
    return true;  // keep backlight on
  } else {
    return false; // turn backlight off
  }
}

/*--------------------------------------------------------------------------------
 * Redraw the display panel when waking up from sleep
 *--------------------------------------------------------------------------------*/
void ui_redisplay(void) {
  lv_disp_trig_activity(NULL);
  lv_disp_load_scr(lv_scr_act());
}

/*--------------------------------------------------------------------------------
 * Start to play with the specified track
 *--------------------------------------------------------------------------------*/
void ui_set_playNo(uint32_t track_id) {
  // start the specified track to play
  player.SetPlayNo(track_id);

  // update ui_control
  ui_control.playNo = ui_control.focusNo = track_id;
  display_picture(track_id);

  // update the look of the play button
  if (ui_state != UI_STATE_PLAY) {
    lv_obj_set_state(ui_ButtonPlay, LV_STATE_CHECKED, true);
    ui_state = UI_STATE_PLAY;
  }
}

/*--------------------------------------------------------------------------------
 * Get the latest information on MP3Player
 *--------------------------------------------------------------------------------*/
uint32_t ui_get_playNo(void) {
  return player.GetPlayNo();
}

uint32_t ui_get_counts(void) {
  return player.GetCounts();
}

/*--------------------------------------------------------------------------------
 * Get ID3 tags (title, album, artist) from the file specified by id
 *--------------------------------------------------------------------------------*/
void ui_get_id3tags(uint32_t track_id, ID3Tags_t &tags) {
  player.GetID3Tags(track_id, tags);
}

/*--------------------------------------------------------------------------------
 * Optional functions for audio-I2S (defined in CYD_Audio.h as a weak function)
 * Note: These functions will be executed in the context of CORE 1.
 *--------------------------------------------------------------------------------*/
void audio_id3data(const char *info) {
  // Avoid a race condition with ui_state set by audio_eof_mp3()
  if (ui_state == UI_STATE_PLAY) {
    char *p;
    if (p = strstr(info, "Title: ")) {
      id3tags.title = p + 7;
    } else
    if (p = strstr(info, "Artist: ")) {
      id3tags.artist = p + 8;
    } else
    if (p = strstr(info, "Album: ")) {
      id3tags.album = p + 7;
      ui_state = UI_STATE_ID3;
    }
  }
}

void audio_eof_mp3(const char *info) {
  ui_state = UI_STATE_EOF;
  if (!player.IsLastSong() || ui_option.repeat) {
    nextState = UI_STATE_NEXT;
  } else {
    nextState = UI_STATE_STOP;
  }
}