// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#include <lvgl.h>
#include "ui_helpers.h"
#include "ui_events.h"

#include "../debug.h"

// Arrow button
#define SHOW_ARROW_BUTTON false

// Screen size / coordinate
#define SCREEN_WIDTH      240
#define SCREEN_HEIGHT     320
#define LV_PCT_X(a)       (SCREEN_WIDTH  * (a) / 100) // for LV_STYLE_CONST_X
#define LV_PCT_Y(a)       (SCREEN_HEIGHT * (a) / 100) // for LV_STYLE_CONST_Y
#define ICON_OFFSET_R     (SCREEN_WIDTH / 2 - 24) // need LV_ALIGN_CENTER
#define ICON_OFFSET_L     (24 - SCREEN_WIDTH / 2) // need LV_ALIGN_CENTER
#define OPTIONS_WIDTH     100
#define ALBUM_CELL_HEIGHT 32

#define UI_COLOR_BACKGROUND   { .blue = 0xf5, .green = 0xf5, .red = 0xf5 }  // lv_color_hex(0xf5f5f5)
#define UI_COLOR_SLIDER       { .blue = 0x00, .green = 0x00, .red = 0x00 }  // lv_color_hex(0x000000)
#define UI_COLOR_CHECKBOX     { .blue = 0xff, .green = 0x40, .red = 0x40 }  // lv_color_hex(0x4040ff)
#define UI_COLOR_LIST_DEFAULT { .blue = 0x7f, .green = 0x5a, .red = 0x5a }  // lv_color_hex(0x5a5a7f)
#define UI_COLOR_LIST_PRESSED { .blue = 0x65, .green = 0x49, .red = 0x4c }  // lv_color_hex(0x4c4965)
#define UI_COLOR_LIST_SHADOW  { .blue = 0x4b, .green = 0x2d, .red = 0x2d }  // lv_color_hex(0x2d2d4b)
#define UI_COLOR_LIST_ARTIST  { .blue = 0xbe, .green = 0xb0, .red = 0xb1 }  // lv_color_hex(0xb1b0be)
#define UI_COLOR_LIST_SLIDER  { .blue = 0xee, .green = 0xee, .red = 0xee }  // lv_color_hex(0xeeeeee)

// Custom font
#define CUSTOM_FONT_SMALL   noto_sans_jp_4bit_jis1_12
#define CUSTOM_FONT_MEDIUM  noto_sans_jp_4bit_jis1_14

LV_FONT_DECLARE(CUSTOM_FONT_SMALL);
LV_FONT_DECLARE(CUSTOM_FONT_MEDIUM);

// SCREEN: ui_ScreenMain
extern lv_obj_t *ui_ScreenMain;
extern lv_obj_t *ui_MusicTitle;
extern lv_obj_t *ui_ElapsedStart;
extern lv_obj_t *ui_ElapsedEnd;
extern lv_obj_t *ui_ButtonPlay;
extern lv_obj_t *ui_ElapsedBar;
extern lv_obj_t *ui_Volume;
extern lv_obj_t *ui_AlbumImage;
void ui_ScreenMain_screen_init(void);
void ui_event_ScreenMain  (lv_event_t *e);
void ui_event_ButtonPlay  (lv_event_t *e);
void ui_event_Volume      (lv_event_t *e);
void ui_event_ElapsedBar  (lv_event_t *e);
void ui_event_GoAlbumList (lv_event_t *e);
void ui_event_GoPlayList  (lv_event_t *e);
void ui_event_GoOptions   (lv_event_t *e);
void ui_event_Favorite    (lv_event_t *e);
void ui_event_Repeat      (lv_event_t *e);
void ui_event_Shuffle     (lv_event_t *e);
void ui_event_ButtonNext  (lv_event_t *e);
void ui_event_ButtonPrev  (lv_event_t *e);
void ui_event_VolumeMax   (lv_event_t *e);
void ui_event_VolumeMin   (lv_event_t *e);

// SCREEN: ui_ScreenAlbumList
extern lv_obj_t *ui_ScreenAlbumList;
void ui_event_ScreenAlbumList(lv_event_t *e);
void ui_ScreenAlbumList_screen_init  (void);
void ui_ScreenAlbumList_screen_deinit(void);
void ui_ScreenAlbumList_create_list(const char *root);

// SCREEN: ui_ScreenPlayList
extern lv_obj_t *ui_ScreenPlayList;
void ui_ScreenPlayList_screen_init  (void);
void ui_ScreenPlayList_screen_deinit(void);
void ui_event_ScreenPlayList(lv_event_t *e);
void ui_event_PlayList_Heart(lv_event_t *e);
void ui_event_PlayListToMain(lv_event_t *e);
void ui_list_update_icon    (uint32_t track_id, bool state);
void ui_list_update_cell    (uint32_t track_id, bool state);
void ui_list_update_play    (uint32_t track_id, bool state);
void ui_list_focus_playing  (uint32_t track_id);
void ui_list_update_duration(uint32_t track_id, uint32_t duration);

// SCREEN: ui_ScreenOptions
extern lv_obj_t *ui_ScreenOptions;
void ui_event_ScreenOptions(lv_event_t *e);
void ui_ScreenOptions_screen_init  (void);
void ui_ScreenOptions_screen_deinit(void);
void ui_set_option_backlight(void);
void ui_set_option_sleeptime(void);

// IMAGES
LV_IMAGE_DECLARE(img_album);            // assets/icons/img_album.png
LV_IMAGE_DECLARE(img_heart_off);        // assets/icons/img_heart_off.png
LV_IMAGE_DECLARE(img_heart_on);         // assets/icons/img_heart_on.png
LV_IMAGE_DECLARE(img_repeat);           // assets/icons/img_repeat.png
LV_IMAGE_DECLARE(img_shuffle);          // assets/icons/img_shuffle.png
LV_IMAGE_DECLARE(img_play);             // assets/icons/img_play.png
LV_IMAGE_DECLARE(img_pause);            // assets/icons/img_pause.png
LV_IMAGE_DECLARE(img_skip_next);        // assets/icons/img_skip_next.png
LV_IMAGE_DECLARE(img_skip_prev);        // assets/icons/img_skip_prev.png
LV_IMAGE_DECLARE(img_vol_max);          // assets/icons/img_vol_max.png
LV_IMAGE_DECLARE(img_vol_min);          // assets/icons/img_vol_min.png
LV_IMAGE_DECLARE(img_menu_up);          // assets/icons/img_menu_up.png
LV_IMAGE_DECLARE(img_menu_down);        // assets/icons/img_menu_down.png
LV_IMAGE_DECLARE(img_menu_right);       // assets/icons/img_menu_right.png
LV_IMAGE_DECLARE(img_menu_left);        // assets/icons/img_menu_left.png
LV_IMAGE_DECLARE(img_menu_dot);         // assets/icons/img_menu_dot.png
LV_IMAGE_DECLARE(img_bluetooth_on);     // assets/icons/img_bluetooth_on.png
LV_IMAGE_DECLARE(img_bluetooth_off);    // assets/icons/img_bluetooth_off.png
LV_IMAGE_DECLARE(img_heart_off_small);  // assets/icons/img_heart_off_small.png
LV_IMAGE_DECLARE(img_heart_on_small);   // assets/icons/img_heart_on_small.png
LV_IMAGE_DECLARE(img_list_play);        // assets/icons/img_list_play.png
LV_IMAGE_DECLARE(img_list_pause);       // assets/icons/img_list_pause.png
LV_IMAGE_DECLARE(img_rotate_folder);    // assets/icons/img_rotate_folder.png
LV_IMAGE_DECLARE(img_rotate_check);     // assets/icons/img_rotate_check.png
LV_IMAGE_DECLARE(img_lv_demo_music_list_border);

// UI STATE
typedef enum {
  UI_STATE_INIT,
  UI_STATE_START,
  UI_STATE_IDLE,
  UI_STATE_PLAY,
  UI_STATE_STOP,
  UI_STATE_PAUSE,
  UI_STATE_RESUME,
  UI_STATE_NEXT,
  UI_STATE_PREV,
  UI_STATE_AWAKE,
  UI_STATE_SLEEP,
  UI_STATE_BLOFF,
  UI_STATE_ID3,
  UI_STATE_EOF,
  UI_STATE_ERROR,
} UI_State_t;

// UI INIT
void ui_init(void);

// Custom Functions
UI_State_t ui_loop(void);
void ui_redisplay(void);
void ui_set_playNo(uint32_t playNo);

uint32_t ui_get_playNo(void);
uint32_t ui_get_counts(void);

// Variables
typedef struct {
  bool      shuffle;
  bool      favorite;
  uint8_t   repeat;
  uint8_t   selectPlaylist;
  uint8_t   selectBacklight;
  uint8_t   selectSleepTimer;
} UI_Option_t;

typedef struct {
  uint32_t  top;
  uint32_t  end;
  uint32_t  playNo;
  uint32_t  focusNo;
  uint32_t  backlightTimer;
  uint32_t  sleepStart;
  uint32_t  sleepTimer;
} UI_Control_t;

extern UI_State_t ui_state;
extern UI_Option_t ui_option;
extern UI_Control_t ui_control;

#endif