// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
void ui_event_ScreenMain(lv_event_t *e);
extern lv_obj_t *ui_ScreenMain;
extern lv_obj_t *ui_ImageAlbum;
extern lv_obj_t *ui_ImageWave;
extern lv_obj_t *ui_MusicTitle;
extern lv_obj_t *ui_ElapsedStart;
extern lv_obj_t *ui_ElapsedEnd;
extern lv_obj_t *ui_MenuDotMain;  void ui_event_MenuDotMain (lv_event_t *e);
extern lv_obj_t *ui_Favourite;    void ui_event_Favourite   (lv_event_t *e);
extern lv_obj_t *ui_Repeat;       void ui_event_Repeat      (lv_event_t *e);
extern lv_obj_t *ui_Shuffle;      void ui_event_Shuffle     (lv_event_t *e);
extern lv_obj_t *ui_ButtonPlay;   void ui_event_ButtonPlay  (lv_event_t *e);
extern lv_obj_t *ui_ButtonNext;   void ui_event_ButtonNext  (lv_event_t *e);
extern lv_obj_t *ui_ButtonPrev;   void ui_event_ButtonPrev  (lv_event_t *e);
extern lv_obj_t *ui_VolumeMax;    void ui_event_VolumeMax   (lv_event_t *e);
extern lv_obj_t *ui_VolumeMin;    void ui_event_VolumeMin   (lv_event_t *e);
extern lv_obj_t *ui_Volume;       void ui_event_Volume      (lv_event_t *e);
extern lv_obj_t *ui_ElapsedBar;   void ui_event_ElapsedBar  (lv_event_t *e);
// CUSTOM VARIABLES

// SCREEN: ui_ScreenOption
void ui_ScreenOption_screen_init(void);
extern lv_obj_t *ui_ScreenOption;     void ui_event_ScreenOption    (lv_event_t *e);
extern lv_obj_t *ui_MenuBackRight;    void ui_event_MenuBackRight   (lv_event_t *e);

extern lv_obj_t *ui_FavoriteLabel;
extern lv_obj_t *ui_FavoriteClearLabel;
extern lv_obj_t *ui_FavoriteClearButton;
extern lv_obj_t *ui_FavoriteNewLabel;
extern lv_obj_t *ui_FavoriteNewButton;
extern lv_obj_t *ui_FavoriteSwitch;   void ui_event_FavoriteSwitch  (lv_event_t *e);
extern lv_obj_t *ui_FavoriteDropdown; void ui_event_FavoriteDropdown(lv_event_t *e);

extern lv_obj_t *ui_BacklightLabel;
extern lv_obj_t *ui_BacklightRoller;
extern lv_obj_t *ui_BacklightSwitch;  void ui_event_BacklightSwitch (lv_event_t *e);

extern lv_obj_t *ui_SleepTimerLabel;
extern lv_obj_t *ui_SleepTimerRoller;
extern lv_obj_t *ui_SleepTimerSwitch; void ui_event_SleepTimerSwitch(lv_event_t *e);
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPlayList
void ui_ScreenPlayList_screen_init(void);
extern lv_obj_t *ui_ContainerPlayList;
extern lv_obj_t *ui_ScreenPlayList;     void ui_event_ScreenPlayList  (lv_event_t *e);
extern lv_obj_t *ui_MenuBackLeft;       void ui_event_MenuBackLeft    (lv_event_t *e);
extern lv_obj_t *ui_CheckFavorite;      void ui_event_CheckFavorite   (lv_event_t *e);
extern lv_obj_t *ui_MenuBackUp;         void ui_event_MenuBackUp      (lv_event_t *e);
extern lv_obj_t *ui_MenuBackDown;       void ui_event_MenuBackDown    (lv_event_t *e);
#if false
extern lv_obj_t *ui_MenuBluetoothOn;    void ui_event_MenuBluetoothOn ( lv_event_t * e);
extern lv_obj_t *ui_MenuBluetoothOff;   void ui_event_MenuBluetoothOff( lv_event_t * e);
#endif
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_album_png);    // assets/album.png
LV_IMG_DECLARE(ui_img_wave_png);     // assets/wave.png
LV_IMG_DECLARE(ui_img_menu_png);     // assets/menu.png
LV_IMG_DECLARE(ui_img_511832737);    // assets/heart-off.png
LV_IMG_DECLARE(ui_img_1050326551);   // assets/heart-on.png
LV_IMG_DECLARE(ui_img_repeat_png);   // assets/repeat.png
LV_IMG_DECLARE(ui_img_shuffle_png);  // assets/shuffle.png
LV_IMG_DECLARE(ui_img_play_png);     // assets/play.png
LV_IMG_DECLARE(ui_img_pause_png);    // assets/pause.png
LV_IMG_DECLARE(ui_img_715969206);    // assets/skip-next.png
LV_IMG_DECLARE(ui_img_1076165770);   // assets/skip-prev.png
LV_IMG_DECLARE(ui_img_1994412056);   // assets/volume-max.png
LV_IMG_DECLARE(ui_img_2058316518);   // assets/volume-min.png
LV_IMG_DECLARE(ui_img_1710110385);   // assets/back-right.png
LV_IMG_DECLARE(ui_img_713466046);    // assets/back-left.png
LV_IMG_DECLARE(ui_img_1753861343);   // assets/bluetooth-on.png
LV_IMG_DECLARE(ui_img_1837194583);   // assets/bluetooth-off.png
LV_IMG_DECLARE(ui_img_1157704237);   // assets/heart-off-small.png
LV_IMG_DECLARE(ui_img_628457255);    // assets/heart-on-small.png
LV_IMG_DECLARE(ui_img_1668913270);   // assets/back-up.png
LV_IMG_DECLARE(ui_img_365069097);    // assets/back-down.png

// UI INIT
void ui_init(void);

// Custom Functions
bool ui_loop(void);
void ui_redisplay(void);
const char* ui_get_title(uint32_t);
const char* ui_get_artist(uint32_t);
uint32_t ui_get_track_length(uint32_t);

// Custom font
LV_FONT_DECLARE(noto_sans_jp_4bit_jis12_12);
LV_FONT_DECLARE(noto_sans_jp_4bit_jis12_14);

#define CUSTOM_FONT_SMALL   noto_sans_jp_4bit_jis12_12
#define CUSTOM_FONT_MEDIUM  noto_sans_jp_4bit_jis12_14

// Variables
typedef struct {
  bool      enableFavarite;
  bool      enableBacklight;
  bool      enableSleepTimer;
  uint8_t   selectFavarite;
  uint8_t   selectBacklight;
  uint8_t   selectSleepTimer;
} UI_Option_t;

typedef struct {
  uint32_t  playNo;
  uint32_t  sleepTimer;
} UI_Control_t;

extern UI_Option_t  ui_option;
extern UI_Control_t ui_control;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
