// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenMain
extern lv_obj_t *ui_ScreenMain;
extern lv_obj_t *ui_ImageAlbum;
extern lv_obj_t *ui_ImageWave;
extern lv_obj_t *ui_MusicTitle;
extern lv_obj_t *ui_ElapsedStart;
extern lv_obj_t *ui_ElapsedEnd;
extern lv_obj_t *ui_ButtonPlay;
extern lv_obj_t *ui_ElapsedBar;
extern lv_obj_t *ui_Volume;
void ui_ScreenMain_screen_init(void);
void ui_event_ScreenMain  (lv_event_t *e);
void ui_event_ButtonPlay  (lv_event_t *e);
void ui_event_Volume      (lv_event_t *e);
void ui_event_ElapsedBar  (lv_event_t *e);
void ui_event_MenuDotMain (lv_event_t *e);
void ui_event_Favorite    (lv_event_t *e);
void ui_event_Repeat      (lv_event_t *e);
void ui_event_Shuffle     (lv_event_t *e);
void ui_event_ButtonNext  (lv_event_t *e);
void ui_event_ButtonPrev  (lv_event_t *e);
void ui_event_VolumeMax   (lv_event_t *e);
void ui_event_VolumeMin   (lv_event_t *e);
// CUSTOM VARIABLES

// SCREEN: ui_ScreenOption
extern lv_obj_t *ui_ScreenOption;
extern lv_obj_t *ui_BacklightRoller;
extern lv_obj_t *ui_SleepTimerRoller;
extern lv_obj_t *ui_FavoriteNewButton;
extern lv_obj_t *ui_FavoriteClearButton;
void ui_ScreenOption_screen_init(void);
void ui_event_ScreenOption      (lv_event_t *e);
void ui_event_OptionToMainRight (lv_event_t *e);
void ui_event_FavoriteDropdown  (lv_event_t *e);
void ui_event_FavoriteSwitch    (lv_event_t *e);
void ui_event_BacklightSwitch   (lv_event_t *e);
void ui_event_SleepTimerSwitch  (lv_event_t *e);
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPlayList
extern lv_obj_t *ui_ScreenPlayList;
extern lv_obj_t *ui_ContainerPlayList;
extern lv_obj_t *ui_PlayListToMainUp;
extern lv_obj_t *ui_PlayListToMainDown;
void ui_ScreenPlayList_screen_init(void);
void ui_event_PlayListToMainUp  (lv_event_t *e);
void ui_event_PlayListToMainDown(lv_event_t *e);
void ui_list_update_icon(uint32_t track_id, bool state);
void ui_list_update_cell(uint32_t track_id, bool state);
void ui_list_update_play(uint32_t track_id, bool state);
#if false
void ui_event_MenuBackToLeft    (lv_event_t *e);
void ui_event_MenuBluetoothOn   (lv_event_t *e);
void ui_event_MenuBluetoothOff  (lv_event_t *e);
#endif
// CUSTOM VARIABLES

// EVENTS

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_album_png);    // assets/album.png
LV_IMG_DECLARE(ui_img_wave_png);     // assets/wave.png
LV_IMG_DECLARE(ui_img_menu_png);     // assets/menu.png
LV_IMG_DECLARE(ui_img_511832737);    // assets/heart-off.png
LV_IMG_DECLARE(ui_img_1050326551);   // assets/heart-on.png
LV_IMG_DECLARE(ui_img_repeat_png);   // assets/repeat.png
LV_IMG_DECLARE(ui_img_shuffle_png);  // assets/shuffle.png
LV_IMG_DECLARE(ui_img_play_png);     // assets/play.png
LV_IMG_DECLARE(ui_img_pause_png);    // assets/pause.png
LV_IMG_DECLARE(ui_img_715969206);    // assets/skip-next.png
LV_IMG_DECLARE(ui_img_1076165770);   // assets/skip-prev.png
LV_IMG_DECLARE(ui_img_1994412056);   // assets/volume-max.png
LV_IMG_DECLARE(ui_img_2058316518);   // assets/volume-min.png
LV_IMG_DECLARE(ui_img_1710110385);   // assets/back-right.png
LV_IMG_DECLARE(ui_img_713466046);    // assets/back-left.png
LV_IMG_DECLARE(ui_img_1753861343);   // assets/bluetooth-on.png
LV_IMG_DECLARE(ui_img_1837194583);   // assets/bluetooth-off.png
LV_IMG_DECLARE(ui_img_1157704237);   // assets/heart-off-small.png
LV_IMG_DECLARE(ui_img_628457255);    // assets/heart-on-small.png
LV_IMG_DECLARE(ui_img_1668913270);   // assets/back-up.png
LV_IMG_DECLARE(ui_img_365069097);    // assets/back-down.png
LV_IMG_DECLARE(ui_img_list_play);    // assets/list-play.png
LV_IMG_DECLARE(ui_img_list_pause);   // assets/list-pause.png

// UI INIT
void ui_init(void);

// Custom Functions
bool ui_loop(void);
void ui_redisplay(void);

const char*     ui_get_title (uint32_t);
const char*     ui_get_artist(uint32_t);
const char*     ui_get_album (uint32_t);
const uint32_t  ui_get_duration(uint32_t);
const uint32_t  ui_get_counts(void);
uint32_t        ui_get_playNo(void);
void            ui_set_playNo(uint32_t playNo);

#define UI_COLOR_BACKGROUND   lv_color_hex(0xffffff)
#define UI_COLOR_SLIDER       lv_color_hex(0x000000)
#define UI_COLOR_CHECKBOX     lv_color_hex(0x4040ff)
#define UI_COLOR_LIST_DEFAULT lv_color_hex(0x5a5a7f)
#define UI_COLOR_LIST_PRESSED lv_color_hex(0x4c4965)
#define UI_COLOR_LIST_SHADOW  lv_color_hex(0x2d2d4b)
#define UI_COLOR_LIST_ARTIST  lv_color_hex(0xb1b0be)
#define UI_COLOR_LIST_SLIDER  lv_color_hex(0xeeeeee)

#define CUSTOM_FONT_SMALL   noto_sans_jp_4bit_jis1_12
#define CUSTOM_FONT_MEDIUM  noto_sans_jp_4bit_jis1_14

// Custom font
LV_FONT_DECLARE(CUSTOM_FONT_SMALL);
LV_FONT_DECLARE(CUSTOM_FONT_MEDIUM);

typedef enum {
  UI_STATE_INIT,
  UI_STATE_IDLE,
  UI_STATE_PLAY,
  UI_STATE_STOP,
  UI_STATE_PAUSE,
  UI_STATE_RESUME,
  UI_STATE_NEXT,
  UI_STATE_PREV,
  UI_STATE_SLEEP,
  UI_STATE_WAKEUP,
  UI_STATE_ID3DATA,
} UI_State_t;

// Variables
typedef struct {
  bool      shuffle;
  bool      repeat;
  bool      favorite;
  bool      backlight;
  bool      sleepTimer;
  uint8_t   selectFavarite;
  uint8_t   selectBacklight;
  uint8_t   selectSleepTimer;
} UI_Option_t;

typedef struct {
  uint32_t  selectedNo;
  uint32_t  sleepTimer;
} UI_Control_t;

extern UI_State_t ui_state;
extern UI_Option_t ui_option;
extern UI_Control_t ui_control;

#endif