// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include <stdio.h>  // for sprintf(), printf()

// defined in ui.cpp
#include "../CYD_MP3Player.h"
extern void ui_get_id3tags(uint32_t track_id, ID3Tags_t &tags);

/**********************
 *      MACROS
 **********************/
#define LIST_BACK_TO_HANDLE_SIZE  25  // back-up.png/back-down.png: 20x20
#define LIST_FONT_SMALL_HEIGHT    17  // for font size: 12px
#define LIST_FONT_MEDIUM_HEIGHT   22  // for font size: 14px
#define LIST_LABEL_MARGINE        100 // left(50) + right(50)
#define LIST_CELL_HEIGHT          60  // column(3) x rol(2)
#define LIST_CELL_VIEWS           5   // LIST_CELL_HEIGHT * LIST_CELL_VIEWS + LIST_BACK_TO_HANDLE_SIZE
#define LIST_CELL_SPARE           2   // 1 <= LIST_CELL_SPARE <= 2

/**********************
 *  STATIC VARIABLES
 **********************/
static lv_obj_t *play_list;
static lv_obj_t *slider;
static lv_style_t style_button;
static lv_style_t style_button_pressed;
static lv_style_t style_button_checked;
//static lv_style_t style_button_disable;
static lv_style_t style_title;
static lv_style_t style_artist;
static lv_style_t style_time;
static lv_style_t style_heart;
static lv_style_t style_menu_back;
LV_IMAGE_DECLARE(img_lv_demo_music_list_border);

static int32_t top_num, end_num; // hold the the highest/lowest number currently loaded in the playlist
static bool update_scroll_running = false;

/**********************
 *  GLOBAL FUNCTIONS
 **********************/
void ui_list_update_icon(uint32_t track_id, bool state) {
  if (top_num <= track_id && track_id <= end_num) {
    lv_obj_t* cell = lv_obj_get_child(play_list, track_id - top_num);
    if (cell) {
      lv_obj_t* icon = lv_obj_get_child(cell, 0);
      if (state) {
        lv_image_set_src(icon, &ui_img_list_pause);
      } else {
        lv_image_set_src(icon, &ui_img_list_play);
      }
    }
  }
}

void ui_list_update_cell(uint32_t track_id, bool state) {
  if (top_num <= track_id && track_id <= end_num) {
    lv_obj_t* cell = lv_obj_get_child(play_list, track_id - top_num);
    if (cell) {
      lv_obj_t* title  = lv_obj_get_child(cell, 1);
      lv_obj_t* artist = lv_obj_get_child(cell, 2);

      if (state) {
        lv_label_set_long_mode(title,  LV_LABEL_LONG_SCROLL_CIRCULAR);
        lv_label_set_long_mode(artist, LV_LABEL_LONG_SCROLL_CIRCULAR);
        lv_obj_add_state(cell, LV_STATE_CHECKED);
      } else {
        lv_label_set_long_mode(title,  LV_LABEL_LONG_DOT);
        lv_label_set_long_mode(artist, LV_LABEL_LONG_DOT);
        lv_obj_remove_state(cell, LV_STATE_CHECKED);
      }
    }
  }
}

void ui_list_update_play(uint32_t track_id, bool state) {
  if (top_num <= track_id && track_id <= end_num) {
    lv_obj_t* cell = lv_obj_get_child(play_list, track_id - top_num);
    if (cell) {
      lv_obj_t* icon   = lv_obj_get_child(cell, 0);
      lv_obj_t* title  = lv_obj_get_child(cell, 1);
      lv_obj_t* artist = lv_obj_get_child(cell, 2);

      if (state) {
        lv_image_set_src(icon, &ui_img_list_pause);
        lv_label_set_long_mode(title,  LV_LABEL_LONG_SCROLL_CIRCULAR);
        lv_label_set_long_mode(artist, LV_LABEL_LONG_SCROLL_CIRCULAR);
        lv_obj_add_state(cell, LV_STATE_CHECKED);
        lv_obj_scroll_to_view(cell, LV_ANIM_ON);
      } else {
        lv_image_set_src(icon, &ui_img_list_play);
        lv_label_set_long_mode(title,  LV_LABEL_LONG_DOT);
        lv_label_set_long_mode(artist, LV_LABEL_LONG_DOT);
        lv_obj_remove_state(cell, LV_STATE_CHECKED);
      }
    }
  }
}

/**********************
 *   STATIC FUNCTIONS
 **********************/
static void list_click_event_cb(lv_event_t* e) {
  uint32_t track_id = (uint32_t)lv_event_get_user_data(e);

  lv_point_t p;
  lv_indev_get_point(lv_indev_get_act(), &p);

  // if the clicked coordinates within the icon area...
  if (p.x <= ui_img_list_play.header.w) {
    // if currently playing...
    if (ui_control.playNo == track_id) {
      // execute pause/resume
      ui_state = (ui_state == UI_STATE_PLAY ? UI_STATE_PAUSE : UI_STATE_RESUME);
      lv_obj_set_state(ui_ButtonPlay, LV_STATE_CHECKED, ui_state == UI_STATE_PAUSE ? false : true);
    }
    // else select the new track to play
    else {
      ui_list_update_play(ui_control.playNo,  false);
      ui_list_update_cell(ui_control.focusNo, false);
      ui_list_update_play(track_id, true);
      ui_set_playNo(track_id);
    }
  }
  // else just change the focused cell
  else {
    ui_list_update_cell(ui_control.focusNo, false);
    ui_control.focusNo = track_id;
    ui_list_update_cell(track_id, true);
  }
}

static lv_obj_t *add_list_cell(lv_obj_t* parent, uint32_t track_id) {
  ID3Tags_t tags;
  ui_get_id3tags(track_id, tags);

  char time[8];
  uint32_t duration = (uint32_t)tags.meta.duration;
  lv_snprintf(time, sizeof(time), "%" LV_PRIu32 ":%02" LV_PRIu32, duration / 60, duration % 60);

  lv_obj_t* cell = lv_obj_create(parent);
  lv_obj_remove_style_all       (cell);
  lv_obj_set_size               (cell, lv_pct(100), LIST_CELL_HEIGHT);

  lv_obj_add_style              (cell, &style_button, 0);
  lv_obj_add_style              (cell, &style_button_pressed, LV_STATE_PRESSED);
  lv_obj_add_style              (cell, &style_button_checked, LV_STATE_CHECKED);
//lv_obj_add_style              (cell, &style_button_disable, LV_STATE_DISABLED);
  lv_obj_add_event_cb           (cell, list_click_event_cb, LV_EVENT_CLICKED, (void*)track_id);

  lv_obj_t* icon = lv_image_create(cell);
  lv_image_set_src              (icon, &ui_img_list_play);
  lv_obj_set_grid_cell          (icon, LV_GRID_ALIGN_START, 0, 1, LV_GRID_ALIGN_CENTER, 0, 2);

  lv_obj_t* title_label = lv_label_create(cell);
  lv_label_set_text             (title_label, tags.title.c_str());
  lv_label_set_long_mode        (title_label, LV_LABEL_LONG_DOT);
  lv_obj_set_grid_cell          (title_label, LV_GRID_ALIGN_START, 1, 1, LV_GRID_ALIGN_CENTER, 0, 1);
  lv_obj_add_style              (title_label, &style_title, 0);

  lv_obj_t* artist_label = lv_label_create(cell);
  lv_label_set_text_fmt         (artist_label, "%s / %s", tags.artist.c_str(), tags.album.c_str());
  lv_label_set_long_mode        (artist_label, LV_LABEL_LONG_DOT);
  lv_obj_set_grid_cell          (artist_label, LV_GRID_ALIGN_START, 1, 1, LV_GRID_ALIGN_CENTER, 1, 1);
  lv_obj_add_style              (artist_label, &style_artist, 0);

  lv_obj_t* time_label = lv_label_create(cell);
  lv_label_set_text             (time_label, time);
  lv_obj_set_grid_cell          (time_label, LV_GRID_ALIGN_END, 2, 1, LV_GRID_ALIGN_END, 0, 2);
  lv_obj_add_style              (time_label, &style_time, 0);

  lv_obj_t* heart = lv_checkbox_create(cell);
  lv_checkbox_set_text          (heart, "");
  lv_obj_set_state              (heart, LV_STATE_CHECKED, tags.meta.selected);
  lv_obj_set_grid_cell          (heart, LV_GRID_ALIGN_END, 2, 1, LV_GRID_ALIGN_START, 0, 2);
  lv_obj_add_event_cb           (heart, ui_event_PlayList_Heart, LV_EVENT_ALL, (void*)track_id);
  lv_obj_add_style              (heart, &style_heart,       (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_add_style              (heart, &style_heart,       (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_add_style              (heart, &style_heart,       (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_bg_image_src (heart, &ui_img_1157704237, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_src (heart, &ui_img_628457255,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_image_src (heart, &ui_img_1157704237, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);

  lv_obj_t* border = lv_image_create(cell);
  lv_image_set_src              (border, &img_lv_demo_music_list_border);
  lv_image_set_inner_align      (border, LV_IMAGE_ALIGN_TILE);
  lv_obj_set_width              (border, lv_pct(120));
  lv_obj_align                  (border, LV_ALIGN_BOTTOM_MID, 0, 0);
  lv_obj_add_flag               (border, LV_OBJ_FLAG_IGNORE_LAYOUT);

  return cell;
}

static void update_scroll(lv_obj_t *obj) {
  // do not re-enter this function when `lv_obj_scroll_by` triggers this callback again.
  if (update_scroll_running) return;
  update_scroll_running = true;

  int32_t pos;

  /* load items we're getting close to */
  while (end_num < ui_get_counts() - 1 && (pos = lv_obj_get_scroll_bottom(obj)) < (LIST_CELL_HEIGHT)) {
    end_num += 1;
    add_list_cell(obj, end_num);
    lv_obj_update_layout(obj);
    //printf("added end_num: %d, pos: %d\n", end_num, pos);
  }
  while (top_num > 0 && (pos = lv_obj_get_scroll_top(obj)) < (LIST_CELL_HEIGHT)) {
    top_num -= 1;
    int32_t bottom_before = lv_obj_get_scroll_bottom(obj);
    lv_obj_t *new_item = add_list_cell(obj, top_num);
    lv_obj_move_to_index(new_item, 0);
    lv_obj_update_layout(obj);
    int32_t bottom_after = lv_obj_get_scroll_bottom(obj);
    lv_obj_scroll_by(obj, 0, bottom_before - bottom_after, LV_ANIM_OFF);
    //printf("added top_num: %d, pos: %d\n", top_num, pos);
  }

  /* delete far-away items */
  while ((pos = lv_obj_get_scroll_bottom(obj)) > (LIST_CELL_HEIGHT * LIST_CELL_SPARE) && end_num - top_num > (LIST_CELL_VIEWS)) {
    end_num -= 1;
    lv_obj_t *child = lv_obj_get_child(obj, -1);
    lv_obj_delete(child);
    lv_obj_update_layout(obj);
    //printf("deleted end_num: %d, pos: %d\n", end_num, pos);
  }
  while ((pos = lv_obj_get_scroll_top(obj)) > (LIST_CELL_HEIGHT * LIST_CELL_SPARE) && end_num - top_num > (LIST_CELL_VIEWS)) {
    top_num += 1;
    int32_t bottom_before = lv_obj_get_scroll_bottom(obj);
    lv_obj_t *child = lv_obj_get_child(obj, 0);
    lv_obj_delete(child);
    lv_obj_update_layout(obj);
    int32_t bottom_after = lv_obj_get_scroll_bottom(obj);
    lv_obj_scroll_by(obj, 0, bottom_before - bottom_after, LV_ANIM_OFF);
    //printf("deleted top_num: %d, pos: %d\n", top_num, pos);
  }

  update_scroll_running = false;
  ui_list_update_cell(ui_control.focusNo, true);
  ui_list_update_icon(ui_get_playNo(),    true);

  // Update slider
  int32_t top = lv_obj_get_scroll_top(obj) + top_num * LIST_CELL_HEIGHT;
  int32_t end = top + LIST_CELL_VIEWS * LIST_CELL_HEIGHT;
  lv_slider_set_value     (slider, end, LV_ANIM_OFF);
  lv_slider_set_left_value(slider, top, LV_ANIM_OFF);
}

static void scroll_cb(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_SCROLL) {
    lv_obj_t *obj = lv_event_get_target_obj(e);
    update_scroll(obj);
  }
}

/*--------------------------------------------------------------------------------
 * Initialize the style of each cell in the playlist
 *--------------------------------------------------------------------------------*/
static lv_obj_t* ui_ScreenPlayList_list_init(lv_obj_t* parent) {
  static const int32_t grid_cols[] = { LV_GRID_CONTENT, LV_GRID_FR(1), (int32_t)ui_img_1157704237.header.w, LV_GRID_TEMPLATE_LAST };
  static const int32_t grid_rows[] = { LIST_FONT_MEDIUM_HEIGHT, LIST_FONT_SMALL_HEIGHT, LV_GRID_TEMPLATE_LAST };

  lv_style_init                     (&style_button);
  lv_style_set_bg_opa               (&style_button, LV_OPA_TRANSP);
  lv_style_set_grid_column_dsc_array(&style_button, grid_cols);
  lv_style_set_grid_row_dsc_array   (&style_button, grid_rows);
  lv_style_set_grid_row_align       (&style_button, LV_GRID_ALIGN_CENTER);
  lv_style_set_layout               (&style_button, LV_LAYOUT_GRID);
  lv_style_set_pad_right            (&style_button, 20);

  lv_style_init               (&style_button_pressed);
  lv_style_set_bg_opa         (&style_button_pressed, LV_OPA_COVER);
  lv_style_set_bg_color       (&style_button_pressed, UI_COLOR_LIST_DEFAULT);

  lv_style_init               (&style_button_checked);
  lv_style_set_bg_opa         (&style_button_checked, LV_OPA_COVER);
  lv_style_set_bg_color       (&style_button_checked, UI_COLOR_LIST_DEFAULT);
/*
  lv_style_init               (&style_button_disable);
  lv_style_set_text_opa       (&style_button_disable, LV_OPA_40);
  lv_style_set_image_opa      (&style_button_disable, LV_OPA_40);
*/
  lv_style_init               (&style_title);
  lv_style_set_width          (&style_title, lv_obj_get_width (lv_scr_act()) - LIST_LABEL_MARGINE);
  lv_style_set_height         (&style_title, LIST_FONT_MEDIUM_HEIGHT);
  lv_style_set_text_font      (&style_title, &CUSTOM_FONT_MEDIUM);
  lv_style_set_text_color     (&style_title, UI_COLOR_BACKGROUND);

  lv_style_init               (&style_artist);
  lv_style_set_width          (&style_artist, lv_obj_get_width (lv_scr_act()) - LIST_LABEL_MARGINE);
  lv_style_set_height         (&style_artist, LIST_FONT_SMALL_HEIGHT);
  lv_style_set_pad_right      (&style_artist, 5); // gap between artist and time
  lv_style_set_text_font      (&style_artist, &CUSTOM_FONT_SMALL);
  lv_style_set_text_color     (&style_artist, UI_COLOR_LIST_ARTIST);

  lv_style_init               (&style_time);
  lv_style_set_text_font      (&style_time, &CUSTOM_FONT_SMALL);
  lv_style_set_text_color     (&style_time, UI_COLOR_BACKGROUND);

  lv_style_init               (&style_heart);
  lv_style_set_bg_color       (&style_heart, UI_COLOR_BACKGROUND);
  lv_style_set_bg_opa         (&style_heart, 0);
  lv_style_set_border_width   (&style_heart, 0);
  lv_style_set_pad_left       (&style_heart, -5); // slightly offset to the right
  lv_style_set_radius         (&style_heart, LV_RADIUS_CIRCLE);

  lv_style_init               (&style_menu_back);
  lv_style_set_bg_color       (&style_menu_back, UI_COLOR_LIST_DEFAULT);
  lv_style_set_shadow_color   (&style_menu_back, UI_COLOR_LIST_SHADOW);
  lv_style_set_bg_opa         (&style_menu_back, 255);
  lv_style_set_border_width   (&style_menu_back,   0);
  lv_style_set_shadow_opa     (&style_menu_back, 255);
  lv_style_set_shadow_width   (&style_menu_back,   1);
  lv_style_set_shadow_spread  (&style_menu_back,   0);
  lv_style_set_shadow_offset_x(&style_menu_back,   0);
  lv_style_set_pad_left       (&style_menu_back, 249);
  lv_style_set_pad_right      (&style_menu_back,   0);
  lv_style_set_pad_top        (&style_menu_back,   8);
  lv_style_set_pad_bottom     (&style_menu_back,   0);

  // Create an empty transparent container
  lv_obj_t* list = lv_obj_create(parent);
  lv_obj_remove_style_all     (list);
  lv_obj_set_size             (list, lv_pct(100), lv_pct(100));
  lv_obj_set_align            (list, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow        (list, LV_FLEX_FLOW_COLUMN);
  lv_obj_add_event_cb         (list, scroll_cb, LV_EVENT_ALL, NULL);

  // Creating a slider as an alternative to a scrollbar
  slider = lv_slider_create(parent); // attach to ui_ContainerPlayList
  lv_obj_align                (slider, LV_ALIGN_TOP_RIGHT, -2, 0);
  lv_obj_remove_flag          (slider, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_set_width            (slider, 4);
  lv_obj_set_height           (slider, LIST_CELL_VIEWS * LIST_CELL_HEIGHT);
  lv_obj_set_style_radius     (slider, LV_RADIUS_CIRCLE,      (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa     (slider, 0, /* set invisible */ (uint32_t)LV_PART_KNOB      | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color   (slider, UI_COLOR_LIST_SLIDER,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_slider_set_mode          (slider, LV_SLIDER_MODE_RANGE);
  lv_slider_set_range         (slider, ui_get_counts() * LIST_CELL_HEIGHT, 0);

  return list;
}

/*--------------------------------------------------------------------------------
 * Delete all cells and focus the specified cell when it is out of range
 *--------------------------------------------------------------------------------*/
void ui_list_focus_playing(uint32_t track_id) {
  if (track_id < top_num || end_num < track_id) {
    // delete all cells in playlist
    while (lv_obj_get_child_count(play_list)) {
      lv_obj_clean(play_list);
    }

    // update layout before add new cells
    lv_slider_set_value     (slider, 0, LV_ANIM_OFF);
    lv_slider_set_left_value(slider, 0, LV_ANIM_OFF);
    lv_obj_update_layout    (slider);
    lv_obj_update_layout    (play_list);

    // add new cells according to the specified id
    ui_control.focusNo = top_num = end_num = track_id;
    add_list_cell(play_list, top_num);
    update_scroll(play_list);
    ui_list_update_play(track_id, true);
  }
}

/*--------------------------------------------------------------------------------
 * Updates the duration to the specified cell
 *--------------------------------------------------------------------------------*/
void ui_list_update_duration(uint32_t track_id, uint32_t duration) {
  if (top_num <= track_id && track_id <= end_num) {
    lv_obj_t* cell = lv_obj_get_child(play_list, track_id - top_num);
    if (cell) {
      lv_obj_t* time_label = lv_obj_get_child(cell, 3);
      char time[8];
      lv_snprintf(time, sizeof(time), "%" LV_PRIu32 ":%02" LV_PRIu32, duration / 60, duration % 60);
      lv_label_set_text(time_label, time);
    }
  }
}

/*--------------------------------------------------------------------------------
 * This initialization is executed once
 *--------------------------------------------------------------------------------*/
void ui_ScreenPlayList_screen_init(void) {
  ui_ScreenPlayList = lv_obj_create(NULL);
  lv_obj_remove_flag              (ui_ScreenPlayList, LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_set_style_bg_color       (ui_ScreenPlayList, UI_COLOR_LIST_PRESSED,  (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa         (ui_ScreenPlayList, 255,                    (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);

  ui_ContainerPlayList = lv_obj_create(ui_ScreenPlayList);
  lv_obj_remove_style_all         (ui_ContainerPlayList);
  lv_obj_set_height               (ui_ContainerPlayList, lv_obj_get_height(lv_scr_act()) - LIST_BACK_TO_HANDLE_SIZE);
  lv_obj_set_width                (ui_ContainerPlayList, lv_pct(100));
  lv_obj_set_align                (ui_ContainerPlayList, LV_ALIGN_BOTTOM_MID); // or LV_ALIGN_TOP_MID
  lv_obj_remove_flag              (ui_ContainerPlayList, (lv_obj_flag_t)(LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE));

  ui_PlayListToMainUp = lv_checkbox_create(ui_ScreenPlayList);
  lv_checkbox_set_text            (ui_PlayListToMainUp, "");
  lv_obj_set_height               (ui_PlayListToMainUp, LIST_BACK_TO_HANDLE_SIZE);
  lv_obj_set_width                (ui_PlayListToMainUp, lv_pct(110));
  lv_obj_set_align                (ui_PlayListToMainUp, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag                 (ui_PlayListToMainUp, LV_OBJ_FLAG_HIDDEN);

  lv_obj_add_style                (ui_PlayListToMainUp, &style_menu_back,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_add_style                (ui_PlayListToMainUp, &style_menu_back,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_add_style                (ui_PlayListToMainUp, &style_menu_back,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_bg_image_src   (ui_PlayListToMainUp, &ui_img_1668913270, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_src   (ui_PlayListToMainUp, &ui_img_1668913270, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_image_src   (ui_PlayListToMainUp, &ui_img_1668913270, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_shadow_offset_y(ui_PlayListToMainUp, -1,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_offset_y(ui_PlayListToMainUp, -1,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_shadow_offset_y(ui_PlayListToMainUp, -1,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);

  ui_PlayListToMainDown = lv_checkbox_create(ui_ScreenPlayList);
  lv_checkbox_set_text            (ui_PlayListToMainDown, "");
  lv_obj_set_height               (ui_PlayListToMainDown, LIST_BACK_TO_HANDLE_SIZE);
  lv_obj_set_width                (ui_PlayListToMainDown, lv_pct(110));
  lv_obj_set_align                (ui_PlayListToMainDown, LV_ALIGN_TOP_MID);
  lv_obj_add_flag                 (ui_PlayListToMainDown, LV_OBJ_FLAG_HIDDEN);

  lv_obj_add_style                (ui_PlayListToMainDown, &style_menu_back,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_add_style                (ui_PlayListToMainDown, &style_menu_back,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_add_style                (ui_PlayListToMainDown, &style_menu_back,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_bg_image_src   (ui_PlayListToMainDown, &ui_img_365069097,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_src   (ui_PlayListToMainDown, &ui_img_365069097,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_image_src   (ui_PlayListToMainDown, &ui_img_365069097,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_shadow_offset_y(ui_PlayListToMainDown, 1,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_offset_y(ui_PlayListToMainDown, 1,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_shadow_offset_y(ui_PlayListToMainDown, 1,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
#if   false
  lv_obj_t *ui_MenuBackToLeft = lv_checkbox_create(ui_ScreenPlayList);
  lv_checkbox_set_text            (ui_MenuBackToLeft, "");
  lv_obj_set_width                (ui_MenuBackToLeft, 27);
  lv_obj_set_height               (ui_MenuBackToLeft, 27);
  lv_obj_set_x                    (ui_MenuBackToLeft, lv_pct(-40));
  lv_obj_set_y                    (ui_MenuBackToLeft, lv_pct(-44));
  lv_obj_set_align                (ui_MenuBackToLeft, LV_ALIGN_CENTER);
  lv_obj_add_flag                 (ui_MenuBackToLeft, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

  lv_obj_set_style_bg_image_src   (ui_MenuBackToLeft, &ui_img_713466046,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_radius         (ui_MenuBackToLeft, LV_RADIUS_CIRCLE,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_border_width   (ui_MenuBackToLeft, 0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left       (ui_MenuBackToLeft, 8,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right      (ui_MenuBackToLeft, 0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top        (ui_MenuBackToLeft, 8,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom     (ui_MenuBackToLeft, 0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

  lv_obj_set_style_bg_image_src   (ui_MenuBackToLeft, &ui_img_713466046,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_color       (ui_MenuBackToLeft, UI_COLOR_BACKGROUND,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_radius         (ui_MenuBackToLeft, LV_RADIUS_CIRCLE,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_opa         (ui_MenuBackToLeft, 255,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);

  lv_obj_set_style_bg_image_src   (ui_MenuBackToLeft, &ui_img_713466046,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_radius         (ui_MenuBackToLeft, LV_RADIUS_CIRCLE,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_border_width   (ui_MenuBackToLeft,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_left       (ui_MenuBackToLeft, 10,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_right      (ui_MenuBackToLeft,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_top        (ui_MenuBackToLeft, 10,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_bottom     (ui_MenuBackToLeft,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_add_event_cb             (ui_MenuBackToLeft, ui_event_MenuBackToLeft, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_MenuBluetoothOn = lv_checkbox_create(ui_ScreenPlayList);
  lv_checkbox_set_text            (ui_MenuBluetoothOn, "");
  lv_obj_set_width                (ui_MenuBluetoothOn, 27);
  lv_obj_set_height               (ui_MenuBluetoothOn, 27);
  lv_obj_set_x                    (ui_MenuBluetoothOn, lv_pct(40));
  lv_obj_set_y                    (ui_MenuBluetoothOn, lv_pct(-44));
  lv_obj_set_align                (ui_MenuBluetoothOn, LV_ALIGN_CENTER);
  lv_obj_add_flag                 (ui_MenuBluetoothOn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);

  lv_obj_set_style_bg_image_src   (ui_MenuBluetoothOn, &ui_img_1753861343,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_radius         (ui_MenuBluetoothOn, LV_RADIUS_CIRCLE,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_border_width   (ui_MenuBluetoothOn, 0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left       (ui_MenuBluetoothOn, 8,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right      (ui_MenuBluetoothOn, 0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top        (ui_MenuBluetoothOn, 8,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom     (ui_MenuBluetoothOn, 0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

  lv_obj_set_style_bg_image_src   (ui_MenuBluetoothOn, &ui_img_1753861343,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_color       (ui_MenuBluetoothOn, UI_COLOR_BACKGROUND, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_radius         (ui_MenuBluetoothOn, LV_RADIUS_CIRCLE,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_opa         (ui_MenuBluetoothOn, 255,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);

  lv_obj_set_style_bg_image_src   (ui_MenuBluetoothOn, &ui_img_1753861343,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_radius         (ui_MenuBluetoothOn, LV_RADIUS_CIRCLE,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_border_width   (ui_MenuBluetoothOn,  0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_left       (ui_MenuBluetoothOn, 10,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_right      (ui_MenuBluetoothOn,  0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_top        (ui_MenuBluetoothOn, 10,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_bottom     (ui_MenuBluetoothOn,  0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);

  lv_obj_t *ui_MenuBluetoothOff = lv_checkbox_create(ui_ScreenPlayList);
  lv_checkbox_set_text            (ui_MenuBluetoothOff, "");
  lv_obj_set_width                (ui_MenuBluetoothOff, 27);
  lv_obj_set_height               (ui_MenuBluetoothOff, 27);
  lv_obj_set_x                    (ui_MenuBluetoothOff, lv_pct(20));
  lv_obj_set_y                    (ui_MenuBluetoothOff, lv_pct(-44));
  lv_obj_set_align                (ui_MenuBluetoothOff, LV_ALIGN_CENTER);
  lv_obj_add_flag                 (ui_MenuBluetoothOff, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);

  lv_obj_set_style_bg_image_src   (ui_MenuBluetoothOff, &ui_img_1837194583, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_radius         (ui_MenuBluetoothOff, LV_RADIUS_CIRCLE,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_border_width   (ui_MenuBluetoothOff, 0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left       (ui_MenuBluetoothOff, 8,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right      (ui_MenuBluetoothOff, 0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top        (ui_MenuBluetoothOff, 8,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom     (ui_MenuBluetoothOff, 0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

  lv_obj_set_style_bg_image_src   (ui_MenuBluetoothOff, &ui_img_1837194583, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_color       (ui_MenuBluetoothOff, UI_COLOR_BACKGROUND,(uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_radius         (ui_MenuBluetoothOff, LV_RADIUS_CIRCLE,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_opa         (ui_MenuBluetoothOff, 255,                (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);

  lv_obj_set_style_bg_image_src   (ui_MenuBluetoothOff, &ui_img_1837194583, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_radius         (ui_MenuBluetoothOff, LV_RADIUS_CIRCLE,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_border_width   (ui_MenuBluetoothOff,  0,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_left       (ui_MenuBluetoothOff, 10,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_right      (ui_MenuBluetoothOff,  0,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_top        (ui_MenuBluetoothOff,  0,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_bottom     (ui_MenuBluetoothOff,  0,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);

  lv_obj_add_event_cb             (ui_MenuBluetoothOn,  ui_event_MenuBluetoothOn,   LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb             (ui_MenuBluetoothOff, ui_event_MenuBluetoothOff,  LV_EVENT_ALL, NULL);
#endif
  lv_obj_add_event_cb(ui_PlayListToMainUp,    ui_event_PlayListToMainUp,    LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_PlayListToMainDown,  ui_event_PlayListToMainDown,  LV_EVENT_ALL, NULL);

  // Initialize play list container
  play_list = ui_ScreenPlayList_list_init(ui_ContainerPlayList);

  // add new cells according to the specified id
  top_num = end_num = ui_control.playNo;
  add_list_cell(play_list, top_num);
  update_scroll(play_list);
  ui_list_update_play(ui_control.playNo, true);
}