// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "list.h"

// https://github.com/lvgl/lvgl/issues/5047#issuecomment-1874591247
#define USE_CONST_STYLE 1

#define DROPDOWN_WIDTH  100

static lv_obj_t *play_list;

/*--------------------------------------------------------------------------------
 *
 *--------------------------------------------------------------------------------*/
typedef struct {
  const char      *options;
  const uint32_t  time[];
} DropdownOpts_t;

static const DropdownOpts_t opts_backlight = {
  "Disable\n30 sec\n1 min\n2 min\n5 min",
  {
    0,              // Disable
    30 * 1000,      // 30 sec
    60 * 1000,      //  1 min
    60 * 1000 * 2,  //  2 min
    60 * 1000 * 5,  //  5 min
  }
};

static const DropdownOpts_t opts_sleeptime = {
  "Disable\n30 min\n60 min\n90 min\n120 min",
  {
    0,                // Disable
    60 * 1000 *  30,  //  30 min
    60 * 1000 *  60,  //  60 min
    60 * 1000 *  90,  //  90 min
    60 * 1000 * 120,  // 120 min
  }
};

void ui_set_option_backlight(void) {
  ui_control.backlightTimer = opts_backlight.time[ui_option.selectBacklight];
}

void ui_set_option_sleeptime(void) {
  ui_control.sleepTimer = opts_sleeptime.time[ui_option.selectSleepTimer];
}

/*--------------------------------------------------------------------------------
 * Event handlers for UI Options
 *--------------------------------------------------------------------------------*/
static void backlight_cb(lv_event_t *e) {
  DBG_ASSERT(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED);

  lv_obj_t * obj = lv_event_get_target_obj(e);
  ui_option.selectBacklight = lv_dropdown_get_selected(obj);
  ui_set_option_backlight();
}

static void sleeptimer_cb(lv_event_t *e) {
  DBG_ASSERT(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED);

  lv_obj_t * obj = lv_event_get_target_obj(e);
  ui_option.selectSleepTimer = lv_dropdown_get_selected(obj);
  ui_control.sleepStart = millis();
  ui_set_option_sleeptime();
}

static void playlist_cb(lv_event_t *e) {
  DBG_ASSERT(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED);

  lv_obj_t * obj = lv_event_get_target_obj(e);
  ui_option.selectPlaylist = lv_dropdown_get_selected(obj);
}

/*--------------------------------------------------------------------------------
 * Set the pointer to the widget to NULL when its object is deleted
 *--------------------------------------------------------------------------------*/
static void delete_cb(lv_event_t *e) {
  lv_obj_t **obj = (lv_obj_t **)lv_event_get_user_data(e);

#if   false
  static lv_obj_t ** const adrs[] = {
    &ui_ScreenOption,
  };
  for (int i = 0; i < sizeof(adrs) / sizeof(adrs[0]); i++) {
    if (obj == adrs[i]) {
      DBG_EXEC(printf("deleted: %d\n", i));
      break;
    }
  }
#endif

  *obj = NULL;
}

/*--------------------------------------------------------------------------------
 * Initialize / Deinitialize widgets
 *--------------------------------------------------------------------------------*/
void ui_ScreenOption_screen_init(void) {
  if (ui_ScreenOption == NULL) {
    ui_ScreenOption = lv_obj_create(NULL);
    lv_obj_set_style_bg_color     (ui_ScreenOption, UI_COLOR_BACKGROUND, (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_event_cb           (ui_ScreenOption, ui_event_ScreenOption, LV_EVENT_GESTURE, NULL);
    lv_obj_add_event_cb           (ui_ScreenOption, ui_event_ScreenOption, LV_EVENT_SCREEN_LOADED, NULL);
    lv_obj_add_event_cb           (ui_ScreenOption, ui_event_ScreenOption, LV_EVENT_SCREEN_UNLOADED, NULL);
    lv_obj_add_event_cb           (ui_ScreenOption, delete_cb, LV_EVENT_DELETE, (void*)&ui_ScreenOption);

#if !USE_CONST_STYLE
    lv_obj_t *ui_OptionToMainRight = lv_checkbox_create(ui_ScreenOption);
    lv_checkbox_set_text          (ui_OptionToMainRight, "");
    lv_obj_set_width              (ui_OptionToMainRight, 27);
    lv_obj_set_height             (ui_OptionToMainRight, 27);
    lv_obj_set_x                  (ui_OptionToMainRight, lv_pct(42));
    lv_obj_set_y                  (ui_OptionToMainRight, lv_pct(-44));
    lv_obj_set_align              (ui_OptionToMainRight, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_image_src (ui_OptionToMainRight, &img_back_right,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color     (ui_OptionToMainRight, UI_COLOR_BACKGROUND, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_set_style_radius       (ui_OptionToMainRight, LV_RADIUS_CIRCLE,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_set_style_border_width (ui_OptionToMainRight,   0,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top      (ui_OptionToMainRight,   8,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right    (ui_OptionToMainRight,   0,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom   (ui_OptionToMainRight,   0,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left     (ui_OptionToMainRight,   8,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

    lv_obj_set_style_pad_top      (ui_OptionToMainRight,  10,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
    lv_obj_set_style_pad_left     (ui_OptionToMainRight,  10,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);

    lv_obj_set_style_bg_image_src (ui_OptionToMainRight, &img_back_right,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
    lv_obj_set_style_bg_color     (ui_OptionToMainRight, UI_COLOR_BACKGROUND, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
    lv_obj_add_event_cb           (ui_OptionToMainRight, ui_event_OptionToMainRight, LV_EVENT_CLICKED, NULL);
#else
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_WIDTH(27),
      LV_STYLE_CONST_HEIGHT(27),
      LV_STYLE_CONST_X(LV_PCT_X(42)),
      LV_STYLE_CONST_Y(LV_PCT_Y(-44)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_default[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_back_right),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
      LV_STYLE_CONST_BORDER_WIDTH(0),
      LV_STYLE_CONST_PAD_TOP(8),
      LV_STYLE_CONST_PAD_RIGHT(0),
      LV_STYLE_CONST_PAD_BOTTOM(0),
      LV_STYLE_CONST_PAD_LEFT(8),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_pressed[] = {
      LV_STYLE_CONST_PAD_TOP(10),
      LV_STYLE_CONST_PAD_LEFT(10),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_checked[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_back_right),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common,  (void*)style_prop_common );
    static LV_STYLE_CONST_INIT(style_default, (void*)style_prop_default);
    static LV_STYLE_CONST_INIT(style_pressed, (void*)style_prop_pressed);
    static LV_STYLE_CONST_INIT(style_checked, (void*)style_prop_checked);

    lv_obj_t *ui_OptionToMainRight = lv_checkbox_create(ui_ScreenOption);
    lv_checkbox_set_text(ui_OptionToMainRight, "");
    lv_obj_add_style    (ui_OptionToMainRight, &style_common,  (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style    (ui_OptionToMainRight, &style_default, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style    (ui_OptionToMainRight, &style_pressed, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
    lv_obj_add_style    (ui_OptionToMainRight, &style_checked, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
    lv_obj_add_event_cb (ui_OptionToMainRight, ui_event_OptionToMainRight, LV_EVENT_CLICKED, NULL);
#endif
    lv_obj_t * obj = lv_label_create(ui_ScreenOption);
    lv_obj_set_pos(obj, LV_PCT_X(5), LV_PCT_Y(4));
    lv_label_set_text(obj, "Playlist");

    obj = lv_dropdown_create(ui_ScreenOption);
    lv_obj_set_pos(obj, LV_PCT_X(5), LV_PCT_Y(11));
    lv_obj_set_size(obj, DROPDOWN_WIDTH, LV_SIZE_CONTENT);
    lv_obj_add_event_cb(obj, playlist_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_dropdown_set_options(obj, "List 1\nList 2\nList 3");
    lv_dropdown_set_selected(obj, ui_option.selectPlaylist);

    play_list = lv_list_create(ui_ScreenOption);
    lv_obj_set_size(play_list, SCREEN_WIDTH - LV_PCT_X(10), SCREEN_HEIGHT - LV_PCT_Y(50) - 2);
    lv_obj_center(play_list);

    obj = lv_label_create(ui_ScreenOption);
    lv_obj_set_pos(obj, LV_PCT_X(5), LV_PCT_Y(78));
    lv_label_set_text(obj, "Backlight Off");

    obj = lv_dropdown_create(ui_ScreenOption);
    lv_obj_set_pos(obj, LV_PCT_X(5), LV_PCT_Y(85));
    lv_obj_set_size(obj, DROPDOWN_WIDTH, LV_SIZE_CONTENT);
    lv_obj_set_style_text_align(obj, LV_TEXT_ALIGN_CENTER, (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_event_cb(obj, backlight_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_dropdown_set_options_static(obj, opts_backlight.options);
    lv_dropdown_set_selected(obj, ui_option.selectBacklight);
    lv_dropdown_set_dir(obj, LV_DIR_TOP);
    lv_dropdown_set_symbol(obj, LV_SYMBOL_UP);


    obj = lv_label_create(ui_ScreenOption);
    lv_obj_set_pos(obj, LV_PCT_X(57), LV_PCT_Y(78));
    lv_label_set_text(obj, "Sleep Timer");

    obj = lv_dropdown_create(ui_ScreenOption);
    lv_obj_set_pos(obj, SCREEN_WIDTH - DROPDOWN_WIDTH - LV_PCT_X(5), LV_PCT_Y(85));
    lv_obj_set_size(obj, DROPDOWN_WIDTH, LV_SIZE_CONTENT);
    lv_obj_set_style_text_align(obj, LV_TEXT_ALIGN_CENTER, (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_event_cb(obj, sleeptimer_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_dropdown_set_options_static(obj, opts_sleeptime.options);
    lv_dropdown_set_selected(obj, ui_option.selectSleepTimer);
    lv_dropdown_set_dir(obj, LV_DIR_TOP);
    lv_dropdown_set_symbol(obj, LV_SYMBOL_UP);
  }
}

void ui_ScreenOption_screen_deinit(void) {
  if (ui_ScreenOption) {
    lv_obj_delete_async(ui_ScreenOption);
  }
}

/*--------------------------------------------------------------------------------
 * Create selectable playlist
 *--------------------------------------------------------------------------------*/
bool ui_ScreenOption_create_list(const char *root_dir) {
  int depth = 1;
  for (int i = 0; i < strlen(root_dir); i++) {
    if (root_dir[i] == '/') {
      --depth;
    }
  }

  File dir = SD.open(root_dir);
  if (!dir) {
    return false;
  }

  Node *root_node = new Node(root_dir);
  root_node->scan_dir(dir);
  dir.close();
  add_list(root_node, play_list, depth);

  make_subtree(root_node, play_list);
  return true;
}