// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_ScreenMain_screen_init(void) {
  ui_ScreenMain = lv_obj_create(NULL);
  lv_obj_set_style_bg_color(ui_ScreenMain, UI_COLOR_BACKGROUND, (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);

  ui_AlbumImage = lv_image_create(ui_ScreenMain);
  lv_image_set_src(ui_AlbumImage, &img_album);
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_X(0),
      LV_STYLE_CONST_Y(LV_PCT_Y(-29)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common, (void*)style_prop_common);
    lv_obj_add_style(ui_AlbumImage, &style_common, (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
  }

  ui_WaveImage = lv_image_create(ui_ScreenMain);
  lv_image_set_src(ui_WaveImage, &img_wave);
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_HEIGHT(25),
      LV_STYLE_CONST_WIDTH(LV_PCT_X(65)),
      LV_STYLE_CONST_X(0),
      LV_STYLE_CONST_Y(LV_PCT_Y(-6)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common, (void*)style_prop_common);
    lv_obj_add_style(ui_WaveImage, &style_common, (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
  }

  ui_MusicTitle = lv_label_create(ui_ScreenMain);
  lv_label_set_long_mode  (ui_MusicTitle, LV_LABEL_LONG_SCROLL_CIRCULAR);
  lv_label_set_text_static(ui_MusicTitle, "Music Title / Artist / Album Title");
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_HEIGHT(LV_SIZE_CONTENT),
      LV_STYLE_CONST_WIDTH(LV_PCT_X(90)),
      LV_STYLE_CONST_X(0),
      LV_STYLE_CONST_Y(LV_PCT_Y(4)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_TEXT_FONT(&CUSTOM_FONT_MEDIUM),
      LV_STYLE_CONST_TEXT_ALIGN(LV_TEXT_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common, (void*)style_prop_common);
    lv_obj_add_style(ui_MusicTitle, &style_common, (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
  }

  ui_ElapsedStart = lv_label_create(ui_ScreenMain);
  lv_label_set_text_static(ui_ElapsedStart, "0:00");
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_HEIGHT(LV_SIZE_CONTENT),
      LV_STYLE_CONST_WIDTH(LV_SIZE_CONTENT),
      LV_STYLE_CONST_X(LV_PCT_X(-40)),
      LV_STYLE_CONST_Y(LV_PCT_Y(13)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common, (void*)style_prop_common);
    lv_obj_add_style(ui_ElapsedStart, &style_common, (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
  }

  ui_ElapsedEnd = lv_label_create(ui_ScreenMain);
  lv_label_set_text_static(ui_ElapsedEnd, "0:00");
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_HEIGHT(LV_SIZE_CONTENT),
      LV_STYLE_CONST_WIDTH(LV_SIZE_CONTENT),
      LV_STYLE_CONST_X(LV_PCT_X(40)),
      LV_STYLE_CONST_Y(LV_PCT_Y(13)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common, (void*)style_prop_common);
    lv_obj_add_style(ui_ElapsedEnd, &style_common, (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
  }

  ui_ElapsedBar = lv_slider_create(ui_ScreenMain);
  lv_slider_set_value       (ui_ElapsedBar, 0, LV_ANIM_OFF);
  lv_obj_remove_flag        (ui_ElapsedBar, LV_OBJ_FLAG_GESTURE_BUBBLE);
  lv_obj_set_style_bg_color (ui_ElapsedBar, UI_COLOR_SLIDER,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa   (ui_ElapsedBar, 255,              (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa   (ui_ElapsedBar,   0,              (uint32_t)LV_PART_KNOB      | (uint32_t)LV_STATE_DEFAULT);
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_HEIGHT(6),
      LV_STYLE_CONST_WIDTH(LV_PCT_X(60)),
      LV_STYLE_CONST_X(0),
      LV_STYLE_CONST_Y(LV_PCT_Y(13)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common, (void*)style_prop_common);
    lv_obj_add_style(ui_ElapsedBar, &style_common, (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
  }

  // Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
  if (lv_slider_get_mode      (ui_ElapsedBar) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_ElapsedBar, 0, LV_ANIM_OFF);
  if (lv_obj_get_style_pad_top(ui_ElapsedBar, (uint32_t)LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ElapsedBar, lv_obj_get_style_pad_right(ui_ElapsedBar, (uint32_t)LV_PART_MAIN) + 1, (uint32_t)LV_PART_MAIN);

  lv_obj_t *ui_MenuDotMain = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text_static(ui_MenuDotMain, "");
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_WIDTH(27),
      LV_STYLE_CONST_HEIGHT(27),
      LV_STYLE_CONST_X(LV_PCT_X(-40)),
      LV_STYLE_CONST_Y(LV_PCT_Y(-44)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_default[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_menu),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
      LV_STYLE_CONST_BORDER_WIDTH(0),
      LV_STYLE_CONST_PAD_LEFT(8),
      LV_STYLE_CONST_PAD_TOP(8),
      LV_STYLE_CONST_PAD_RIGHT(0),
      LV_STYLE_CONST_PAD_BOTTOM(0),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_pressed[] = {
      LV_STYLE_CONST_PAD_LEFT(10),
      LV_STYLE_CONST_PAD_TOP(10),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_checked[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_menu),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common,  (void*)style_prop_common );
    static LV_STYLE_CONST_INIT(style_default, (void*)style_prop_default);
    static LV_STYLE_CONST_INIT(style_pressed, (void*)style_prop_pressed);
    static LV_STYLE_CONST_INIT(style_checked, (void*)style_prop_checked);

    lv_obj_add_style(ui_MenuDotMain, &style_common,  (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_MenuDotMain, &style_default, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_MenuDotMain, &style_pressed, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
    lv_obj_add_style(ui_MenuDotMain, &style_checked, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  }

  lv_obj_t *ui_Favorite = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text_static(ui_Favorite, "");
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_WIDTH(25),
      LV_STYLE_CONST_HEIGHT(25),
      LV_STYLE_CONST_X(LV_PCT_X(40)),
      LV_STYLE_CONST_Y(LV_PCT_Y(-44)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_default[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_heart_off),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
      LV_STYLE_CONST_BORDER_WIDTH(0),
      LV_STYLE_CONST_PAD_LEFT(8),
      LV_STYLE_CONST_PAD_TOP(8),
      LV_STYLE_CONST_PAD_RIGHT(0),
      LV_STYLE_CONST_PAD_BOTTOM(0),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_pressed[] = {
      LV_STYLE_CONST_PAD_LEFT(10),
      LV_STYLE_CONST_PAD_TOP(10),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_checked[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_heart_on),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common,  (void*)style_prop_common );
    static LV_STYLE_CONST_INIT(style_default, (void*)style_prop_default);
    static LV_STYLE_CONST_INIT(style_pressed, (void*)style_prop_pressed);
    static LV_STYLE_CONST_INIT(style_checked, (void*)style_prop_checked);

    lv_obj_add_style(ui_Favorite, &style_common,  (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Favorite, &style_default, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Favorite, &style_pressed, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
    lv_obj_add_style(ui_Favorite, &style_checked, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  }

  lv_obj_t *ui_Repeat = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text_static (ui_Repeat, "");
  lv_obj_add_state            (ui_Repeat, ui_option.repeat ? LV_STATE_CHECKED : LV_STATE_DEFAULT);
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_WIDTH(25),
      LV_STYLE_CONST_HEIGHT(25),
      LV_STYLE_CONST_X(LV_PCT_X(40)),
      LV_STYLE_CONST_Y(LV_PCT_Y(-15)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_default[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_repeat),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
      LV_STYLE_CONST_BG_IMAGE_OPA(64),
      LV_STYLE_CONST_BORDER_WIDTH(0),
      LV_STYLE_CONST_PAD_LEFT(8),
      LV_STYLE_CONST_PAD_TOP(8),
      LV_STYLE_CONST_PAD_RIGHT(0),
      LV_STYLE_CONST_PAD_BOTTOM(0),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_pressed[] = {
      LV_STYLE_CONST_PAD_LEFT(10),
      LV_STYLE_CONST_PAD_TOP(10),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_checked[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_repeat),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_BG_IMAGE_OPA(255),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common,  (void*)style_prop_common );
    static LV_STYLE_CONST_INIT(style_default, (void*)style_prop_default);
    static LV_STYLE_CONST_INIT(style_pressed, (void*)style_prop_pressed);
    static LV_STYLE_CONST_INIT(style_checked, (void*)style_prop_checked);

    lv_obj_add_style(ui_Repeat, &style_common,  (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Repeat, &style_default, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Repeat, &style_pressed, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
    lv_obj_add_style(ui_Repeat, &style_checked, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  }

  lv_obj_t *ui_Shuffle = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text_static (ui_Shuffle, "");
  lv_obj_add_state            (ui_Shuffle, ui_option.shuffle ? LV_STATE_CHECKED : LV_STATE_DEFAULT);
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_WIDTH(25),
      LV_STYLE_CONST_HEIGHT(25),
      LV_STYLE_CONST_X(LV_PCT_X(-40)),
      LV_STYLE_CONST_Y(LV_PCT_Y(-15)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_default[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_shuffle),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
      LV_STYLE_CONST_BG_IMAGE_OPA(64),
      LV_STYLE_CONST_BORDER_WIDTH(0),
      LV_STYLE_CONST_PAD_LEFT(8),
      LV_STYLE_CONST_PAD_TOP(8),
      LV_STYLE_CONST_PAD_RIGHT(0),
      LV_STYLE_CONST_PAD_BOTTOM(0),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_pressed[] = {
      LV_STYLE_CONST_PAD_LEFT(10),
      LV_STYLE_CONST_PAD_TOP(10),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_checked[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_shuffle),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_BG_IMAGE_OPA(255),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common,  (void*)style_prop_common );
    static LV_STYLE_CONST_INIT(style_default, (void*)style_prop_default);
    static LV_STYLE_CONST_INIT(style_pressed, (void*)style_prop_pressed);
    static LV_STYLE_CONST_INIT(style_checked, (void*)style_prop_checked);

    lv_obj_add_style(ui_Shuffle, &style_common,  (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Shuffle, &style_default, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Shuffle, &style_pressed, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
    lv_obj_add_style(ui_Shuffle, &style_checked, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  }

  ui_ButtonPlay = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text_static(ui_ButtonPlay, "");
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_WIDTH(50),
      LV_STYLE_CONST_HEIGHT(50),
      LV_STYLE_CONST_X(LV_PCT_X(2)),
      LV_STYLE_CONST_Y(LV_PCT_Y(27)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_default[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_play),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
      LV_STYLE_CONST_BORDER_WIDTH(0),
      LV_STYLE_CONST_PAD_LEFT(34),
      LV_STYLE_CONST_PAD_TOP(34),
      LV_STYLE_CONST_PAD_RIGHT(0),
      LV_STYLE_CONST_PAD_BOTTOM(0),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_checked[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_pause),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common,  (void*)style_prop_common );
    static LV_STYLE_CONST_INIT(style_default, (void*)style_prop_default);
    static LV_STYLE_CONST_INIT(style_checked, (void*)style_prop_checked);

    lv_obj_add_style(ui_ButtonPlay, &style_common,  (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_ButtonPlay, &style_default, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_ButtonPlay, &style_checked, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  }

  lv_obj_t *ui_ButtonNext = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text_static(ui_ButtonNext, "");
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_WIDTH(45),
      LV_STYLE_CONST_HEIGHT(45),
      LV_STYLE_CONST_X(LV_PCT_X(26)),
      LV_STYLE_CONST_Y(LV_PCT_Y(28)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_default[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_skip_next),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
      LV_STYLE_CONST_BORDER_WIDTH(0),
      LV_STYLE_CONST_PAD_LEFT(24),
      LV_STYLE_CONST_PAD_TOP(24),
      LV_STYLE_CONST_PAD_RIGHT(0),
      LV_STYLE_CONST_PAD_BOTTOM(0),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_pressed[] = {
      LV_STYLE_CONST_PAD_LEFT(24),
      LV_STYLE_CONST_PAD_TOP(24),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_checked[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_skip_next),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common,  (void*)style_prop_common );
    static LV_STYLE_CONST_INIT(style_default, (void*)style_prop_default);
    static LV_STYLE_CONST_INIT(style_pressed, (void*)style_prop_pressed);
    static LV_STYLE_CONST_INIT(style_checked, (void*)style_prop_checked);

    lv_obj_add_style(ui_ButtonNext, &style_common,  (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_ButtonNext, &style_default, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_ButtonNext, &style_pressed, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
    lv_obj_add_style(ui_ButtonNext, &style_checked, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  }

  lv_obj_t *ui_ButtonPrev = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text_static(ui_ButtonPrev, "");
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_WIDTH(45),
      LV_STYLE_CONST_HEIGHT(45),
      LV_STYLE_CONST_X(LV_PCT_X(-22)),
      LV_STYLE_CONST_Y(LV_PCT_Y(28)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_default[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_skip_prev),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
      LV_STYLE_CONST_BORDER_WIDTH(0),
      LV_STYLE_CONST_PAD_LEFT(24),
      LV_STYLE_CONST_PAD_TOP(24),
      LV_STYLE_CONST_PAD_RIGHT(0),
      LV_STYLE_CONST_PAD_BOTTOM(0),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_pressed[] = {
      LV_STYLE_CONST_PAD_LEFT(26),
      LV_STYLE_CONST_PAD_TOP(26),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_checked[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_skip_prev),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common,  (void*)style_prop_common );
    static LV_STYLE_CONST_INIT(style_default, (void*)style_prop_default);
    static LV_STYLE_CONST_INIT(style_pressed, (void*)style_prop_pressed);
    static LV_STYLE_CONST_INIT(style_checked, (void*)style_prop_checked);

    lv_obj_add_style(ui_ButtonPrev, &style_common,  (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_ButtonPrev, &style_default, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_ButtonPrev, &style_pressed, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
    lv_obj_add_style(ui_ButtonPrev, &style_checked, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  }

  lv_obj_t *ui_VolumeMax = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text_static(ui_VolumeMax, "");
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_WIDTH(40),
      LV_STYLE_CONST_HEIGHT(40),
      LV_STYLE_CONST_X(LV_PCT_X(40)),
      LV_STYLE_CONST_Y(LV_PCT_Y(43)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_default[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_vol_max),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
      LV_STYLE_CONST_BORDER_WIDTH(0),
      LV_STYLE_CONST_PAD_LEFT(22),
      LV_STYLE_CONST_PAD_TOP(22),
      LV_STYLE_CONST_PAD_RIGHT(0),
      LV_STYLE_CONST_PAD_BOTTOM(0),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_pressed[] = {
      LV_STYLE_CONST_PAD_LEFT(24),
      LV_STYLE_CONST_PAD_TOP(24),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_checked[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_vol_max),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common,  (void*)style_prop_common );
    static LV_STYLE_CONST_INIT(style_default, (void*)style_prop_default);
    static LV_STYLE_CONST_INIT(style_pressed, (void*)style_prop_pressed);
    static LV_STYLE_CONST_INIT(style_checked, (void*)style_prop_checked);

    lv_obj_add_style(ui_VolumeMax, &style_common,  (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_VolumeMax, &style_default, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_VolumeMax, &style_pressed, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
    lv_obj_add_style(ui_VolumeMax, &style_checked, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  }

  lv_obj_t *ui_VolumeMin = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text_static(ui_VolumeMin, "");
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_WIDTH(40),
      LV_STYLE_CONST_HEIGHT(40),
      LV_STYLE_CONST_X(LV_PCT_X(-39)),
      LV_STYLE_CONST_Y(LV_PCT_Y(43)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_default[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_vol_min),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
      LV_STYLE_CONST_BORDER_WIDTH(0),
      LV_STYLE_CONST_PAD_LEFT(22),
      LV_STYLE_CONST_PAD_TOP(22),
      LV_STYLE_CONST_PAD_RIGHT(0),
      LV_STYLE_CONST_PAD_BOTTOM(0),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_pressed[] = {
      LV_STYLE_CONST_PAD_LEFT(24),
      LV_STYLE_CONST_PAD_TOP(24),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_checked[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_vol_min),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common,  (void*)style_prop_common );
    static LV_STYLE_CONST_INIT(style_default, (void*)style_prop_default);
    static LV_STYLE_CONST_INIT(style_pressed, (void*)style_prop_pressed);
    static LV_STYLE_CONST_INIT(style_checked, (void*)style_prop_checked);

    lv_obj_add_style(ui_VolumeMin, &style_common,  (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_VolumeMin, &style_default, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_VolumeMin, &style_pressed, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
    lv_obj_add_style(ui_VolumeMin, &style_checked, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  }

  ui_Volume = lv_slider_create(ui_ScreenMain);
  lv_slider_set_range (ui_Volume, 0, 21); // MP3_VOLUME_MAX (21) is defined in CYD_MP3Player.h
  lv_slider_set_value (ui_Volume, 0, LV_ANIM_OFF);
  lv_obj_remove_flag  (ui_Volume, LV_OBJ_FLAG_GESTURE_BUBBLE);
  {
    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_HEIGHT(8),
      LV_STYLE_CONST_WIDTH(LV_PCT_X(49)),
      LV_STYLE_CONST_X(0),
      LV_STYLE_CONST_Y(LV_PCT_Y(43)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_default[] = {
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_SLIDER),
      LV_STYLE_CONST_BG_OPA(255),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common,  (void*)style_prop_common );
    static LV_STYLE_CONST_INIT(style_default, (void*)style_prop_default);

    lv_obj_add_style(ui_Volume, &style_common,  (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Volume, &style_default, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Volume, &style_default, (uint32_t)LV_PART_KNOB      | (uint32_t)LV_STATE_DEFAULT);
  }

  // Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
  if (lv_slider_get_mode      (ui_Volume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Volume, 0, LV_ANIM_OFF);
  if (lv_obj_get_style_pad_top(ui_Volume, (uint32_t)LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Volume, lv_obj_get_style_pad_right(ui_Volume, (uint32_t)LV_PART_MAIN) + 1, (uint32_t)LV_PART_MAIN);

  lv_obj_add_event_cb(ui_MenuDotMain, ui_event_MenuDotMain, LV_EVENT_CLICKED, NULL);
  lv_obj_add_event_cb(ui_Favorite,    ui_event_Favorite,    LV_EVENT_CLICKED, NULL);
  lv_obj_add_event_cb(ui_Repeat,      ui_event_Repeat,      LV_EVENT_CLICKED, NULL);
  lv_obj_add_event_cb(ui_Shuffle,     ui_event_Shuffle,     LV_EVENT_CLICKED, NULL);
  lv_obj_add_event_cb(ui_ButtonPlay,  ui_event_ButtonPlay,  LV_EVENT_CLICKED, NULL);
  lv_obj_add_event_cb(ui_ButtonNext,  ui_event_ButtonNext,  LV_EVENT_CLICKED, NULL);
  lv_obj_add_event_cb(ui_ButtonPrev,  ui_event_ButtonPrev,  LV_EVENT_CLICKED, NULL);
  lv_obj_add_event_cb(ui_VolumeMax,   ui_event_VolumeMax,   LV_EVENT_CLICKED, NULL);
  lv_obj_add_event_cb(ui_VolumeMin,   ui_event_VolumeMin,   LV_EVENT_CLICKED, NULL);
  lv_obj_add_event_cb(ui_Volume,      ui_event_Volume,      LV_EVENT_VALUE_CHANGED, NULL);
  lv_obj_add_event_cb(ui_ElapsedBar,  ui_event_ElapsedBar,  LV_EVENT_VALUE_CHANGED, NULL);
  lv_obj_add_event_cb(ui_ScreenMain,  ui_event_ScreenMain,  LV_EVENT_GESTURE, NULL);
}