// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include <Arduino.h> // for millis()
#include "ui.h"

//--------------------------------------------------------------------------------
// Offset from the top
//--------------------------------------------------------------------------------
#define OFFSET_TOP  40

//--------------------------------------------------------------------------------
// Contents of dropdown list
//--------------------------------------------------------------------------------
typedef struct {
  const char      *options;
  const uint32_t  time[];
} DropdownOpts_t;

static const DropdownOpts_t opts_backlight = {
  "Disable\n30 sec\n1 min\n2 min\n5 min",
  {
    0,              // Disable
    30 * 1000,      // 30 sec
    60 * 1000,      //  1 min
    60 * 1000 * 2,  //  2 min
    60 * 1000 * 5,  //  5 min
  }
};

static const DropdownOpts_t opts_sleeptime = {
  "Disable\n30 min\n60 min\n90 min\n120 min",
  {
    0,                // Disable
    60 * 1000 *  30,  //  30 min
    60 * 1000 *  60,  //  60 min
    60 * 1000 *  90,  //  90 min
    60 * 1000 * 120,  // 120 min
  }
};

void ui_set_option_backlight(void) {
  ui_control.backlightTimer = opts_backlight.time[ui_option.selectBacklight];
}

void ui_set_option_sleeptime(void) {
  ui_control.sleepTimer = opts_sleeptime.time[ui_option.selectSleepTimer];
}

//--------------------------------------------------------------------------------
// Event handlers for UI Options
//--------------------------------------------------------------------------------
static void backlight_cb(lv_event_t *e) {
  DBG_ASSERT(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED);

  lv_obj_t * obj = lv_event_get_target_obj(e);
  ui_option.selectBacklight = lv_roller_get_selected(obj);
  ui_set_option_backlight();
}

static void sleeptimer_cb(lv_event_t *e) {
  DBG_ASSERT(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED);

  lv_obj_t * obj = lv_event_get_target_obj(e);
  ui_option.selectSleepTimer = lv_roller_get_selected(obj);
  ui_control.sleepStart = millis();
  ui_set_option_sleeptime();
}

//--------------------------------------------------------------------------------
// Set the pointer to the widget to NULL when its object is deleted
//--------------------------------------------------------------------------------
static void delete_cb(lv_event_t *e) {
  lv_obj_t **obj = (lv_obj_t **)lv_event_get_user_data(e);
  static constexpr lv_obj_t ** const adrs[] = {
    &ui_ScreenOptions,
  };

  for (int i = 0; i < sizeof(adrs) / sizeof(adrs[0]); i++) {
    if (obj == adrs[i]) {
      *obj = NULL;
      DBG_EXEC(printf("deleted: %d\n", i));
      return;
    }
  }
  DBG_EXEC(printf("deleted: 0x%x\n", obj));
}

//--------------------------------------------------------------------------------
// Initialize / Deinitialize widgets
//--------------------------------------------------------------------------------
void ui_ScreenOptions_screen_init(void) {
  if (ui_ScreenOptions == NULL) {
    ui_ScreenOptions = lv_obj_create(NULL);
    lv_obj_set_style_bg_color (ui_ScreenOptions, UI_COLOR_BACKGROUND, 0);
    lv_obj_add_event_cb       (ui_ScreenOptions, ui_event_ScreenOptions, LV_EVENT_GESTURE, NULL);
    lv_obj_add_event_cb       (ui_ScreenOptions, ui_event_ScreenOptions, LV_EVENT_SCREEN_UNLOADED, NULL);
    lv_obj_add_event_cb       (ui_ScreenOptions, delete_cb, LV_EVENT_DELETE, (void*)&ui_ScreenOptions);

    //////////////////// Backlight Label ////////////////////
    lv_obj_t *obj = lv_label_create(ui_ScreenOptions);
    lv_obj_set_pos(obj, LV_PCT_X(5), LV_PCT_Y(4) + OFFSET_TOP);
    lv_label_set_text_static(obj, "Backlight Off");

    //////////////////// Backlight Dropdown ////////////////////
    obj = lv_roller_create(ui_ScreenOptions);
    lv_obj_set_pos(obj, LV_PCT_X(5), LV_PCT_Y(11) + OFFSET_TOP);
    lv_obj_set_style_width(obj, OPTIONS_WIDTH, 0);
    lv_obj_add_event_cb(obj, backlight_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_roller_set_options(obj, opts_backlight.options, LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(obj, ui_option.selectBacklight, LV_ANIM_ON);
    lv_roller_set_visible_row_count(obj, 3);

    //////////////////// Sleep Timer Label ////////////////////
    obj = lv_label_create(ui_ScreenOptions);
    lv_obj_set_pos(obj, LV_PCT_X(57), LV_PCT_Y(4) + OFFSET_TOP);
    lv_label_set_text_static(obj, "Sleep Timer");

    //////////////////// Sleep Timer Dropdown ////////////////////
    obj = lv_roller_create(ui_ScreenOptions);
    lv_obj_set_pos(obj, SCREEN_WIDTH - OPTIONS_WIDTH - LV_PCT_X(5), LV_PCT_Y(11) + OFFSET_TOP);
    lv_obj_set_style_width(obj, OPTIONS_WIDTH, 0);
    lv_obj_add_event_cb(obj, sleeptimer_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_roller_set_options(obj, opts_sleeptime.options, LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(obj, ui_option.selectSleepTimer, LV_ANIM_ON);
    lv_roller_set_visible_row_count(obj, 3);
  }
}

void ui_ScreenOptions_screen_deinit(void) {
  if (ui_ScreenOptions) {
    lv_obj_delete_async(ui_ScreenOptions);
  }
}