// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_ScreenMain_screen_init(void) {
  ui_ScreenMain = lv_obj_create(NULL);
  lv_obj_set_style_bg_color     (ui_ScreenMain, UI_COLOR_BACKGROUND,  (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa       (ui_ScreenMain, 255,                  (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_remove_flag            (ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);

  lv_obj_set_style_pad_left     (ui_ScreenMain,  10, (uint32_t)LV_PART_SCROLLBAR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right    (ui_ScreenMain,   0, (uint32_t)LV_PART_SCROLLBAR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top      (ui_ScreenMain,  10, (uint32_t)LV_PART_SCROLLBAR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom   (ui_ScreenMain,   0, (uint32_t)LV_PART_SCROLLBAR | (uint32_t)LV_STATE_DEFAULT);

  ui_AlbumImage = lv_image_create(ui_ScreenMain);
  lv_image_set_src              (ui_AlbumImage, &ui_img_album_png);
  lv_obj_set_x                  (ui_AlbumImage, 0);
  lv_obj_set_y                  (ui_AlbumImage, lv_pct(-29));
  lv_obj_set_align              (ui_AlbumImage, LV_ALIGN_CENTER);
  lv_obj_add_flag               (ui_AlbumImage, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_remove_flag            (ui_AlbumImage, LV_OBJ_FLAG_SCROLLABLE);

  lv_style_init                 (&ui_AlbumStyle);
  lv_style_set_shadow_width     (&ui_AlbumStyle, 10);
  lv_style_set_shadow_offset_y  (&ui_AlbumStyle, 5);
  lv_style_set_shadow_opa       (&ui_AlbumStyle, LV_OPA_50);

  ui_WaveImage = lv_image_create(ui_ScreenMain);
  lv_image_set_src              (ui_WaveImage, &ui_img_wave_png);
  lv_obj_set_height             (ui_WaveImage, 25);
  lv_obj_set_width              (ui_WaveImage, lv_pct(65));
  lv_obj_set_x                  (ui_WaveImage, 0);
  lv_obj_set_y                  (ui_WaveImage, lv_pct(-6));
  lv_obj_set_align              (ui_WaveImage, LV_ALIGN_CENTER);
  lv_obj_remove_flag            (ui_WaveImage, LV_OBJ_FLAG_SCROLLABLE);
  lv_image_set_scale            (ui_WaveImage, 120);
  lv_obj_add_flag               (ui_WaveImage, /* LV_OBJ_FLAG_HIDDEN | */ LV_OBJ_FLAG_CHECKABLE);

  ui_MusicTitle = lv_label_create(ui_ScreenMain);
  lv_obj_set_width              (ui_MusicTitle, lv_pct(90));
  lv_obj_set_height             (ui_MusicTitle, LV_SIZE_CONTENT); // for 14pt bpp=4
  lv_obj_set_x                  (ui_MusicTitle, 0);
  lv_obj_set_y                  (ui_MusicTitle, lv_pct(4));
  lv_obj_set_align              (ui_MusicTitle, LV_ALIGN_CENTER);
  lv_obj_set_style_text_font    (ui_MusicTitle, &CUSTOM_FONT_MEDIUM, 0);
  lv_obj_set_style_text_align   (ui_MusicTitle, LV_TEXT_ALIGN_CENTER, (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
  lv_label_set_long_mode        (ui_MusicTitle, LV_LABEL_LONG_SCROLL_CIRCULAR);
  lv_label_set_text_static      (ui_MusicTitle, "Music Title / Artist / Album Title");

  ui_ElapsedStart = lv_label_create(ui_ScreenMain);
  lv_obj_set_width              (ui_ElapsedStart, LV_SIZE_CONTENT);
  lv_obj_set_height             (ui_ElapsedStart, LV_SIZE_CONTENT);
  lv_obj_set_x                  (ui_ElapsedStart, lv_pct(-40));
  lv_obj_set_y                  (ui_ElapsedStart, lv_pct(13));
  lv_obj_set_align              (ui_ElapsedStart, LV_ALIGN_CENTER);
  lv_label_set_text_static      (ui_ElapsedStart, "0:00");

  ui_ElapsedEnd = lv_label_create(ui_ScreenMain);
  lv_obj_set_width              (ui_ElapsedEnd, LV_SIZE_CONTENT);
  lv_obj_set_height             (ui_ElapsedEnd, LV_SIZE_CONTENT);
  lv_obj_set_x                  (ui_ElapsedEnd, lv_pct(40));
  lv_obj_set_y                  (ui_ElapsedEnd, lv_pct(13));
  lv_obj_set_align              (ui_ElapsedEnd, LV_ALIGN_CENTER);
  lv_label_set_text_static      (ui_ElapsedEnd, "0:00");

  ui_ElapsedBar = lv_slider_create(ui_ScreenMain);
  lv_slider_set_value           (ui_ElapsedBar, 0, LV_ANIM_OFF);
  lv_obj_set_height             (ui_ElapsedBar, 6);
  lv_obj_set_width              (ui_ElapsedBar, lv_pct(60));
  lv_obj_set_x                  (ui_ElapsedBar, 0);
  lv_obj_set_y                  (ui_ElapsedBar, lv_pct(13));
  lv_obj_set_align              (ui_ElapsedBar, LV_ALIGN_CENTER);
  lv_obj_remove_flag            (ui_ElapsedBar, LV_OBJ_FLAG_GESTURE_BUBBLE);
  lv_obj_set_style_radius       (ui_ElapsedBar, LV_RADIUS_CIRCLE, (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color     (ui_ElapsedBar, UI_COLOR_SLIDER,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa       (ui_ElapsedBar, 255,              (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa       (ui_ElapsedBar,   0,              (uint32_t)LV_PART_KNOB      | (uint32_t)LV_STATE_DEFAULT);
  if (lv_slider_get_mode        (ui_ElapsedBar) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_ElapsedBar, 0, LV_ANIM_OFF);

  // Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
  if (lv_obj_get_style_pad_top  (ui_ElapsedBar, (uint32_t)LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ElapsedBar, lv_obj_get_style_pad_right(ui_ElapsedBar, (uint32_t)LV_PART_MAIN) + 1, (uint32_t)LV_PART_MAIN);

  lv_obj_t *ui_MenuDotMain = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text          (ui_MenuDotMain, "");
  lv_obj_set_width              (ui_MenuDotMain, 27);
  lv_obj_set_height             (ui_MenuDotMain, 27);
  lv_obj_set_x                  (ui_MenuDotMain, lv_pct(-40));
  lv_obj_set_y                  (ui_MenuDotMain, lv_pct(-44));
  lv_obj_set_align              (ui_MenuDotMain, LV_ALIGN_CENTER);
  lv_obj_add_flag               (ui_MenuDotMain, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

  lv_obj_set_style_bg_image_src (ui_MenuDotMain, &ui_img_menu_png,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_radius       (ui_MenuDotMain, LV_RADIUS_CIRCLE,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_border_width (ui_MenuDotMain,   0,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left     (ui_MenuDotMain,   8,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right    (ui_MenuDotMain,   0,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top      (ui_MenuDotMain,   8,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom   (ui_MenuDotMain,   0,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

  lv_obj_set_style_bg_image_src (ui_MenuDotMain, &ui_img_menu_png,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_color     (ui_MenuDotMain, UI_COLOR_BACKGROUND, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_radius       (ui_MenuDotMain, LV_RADIUS_CIRCLE,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_opa       (ui_MenuDotMain, 255,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);

  lv_obj_set_style_bg_image_src (ui_MenuDotMain, &ui_img_menu_png,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_radius       (ui_MenuDotMain, LV_RADIUS_CIRCLE,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_border_width (ui_MenuDotMain,  0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_left     (ui_MenuDotMain, 10,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_right    (ui_MenuDotMain,  0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_top      (ui_MenuDotMain, 10,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_bottom   (ui_MenuDotMain,  0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);

  lv_obj_t *ui_Favorite = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text          (ui_Favorite, "");
  lv_obj_set_width              (ui_Favorite, 25);
  lv_obj_set_height             (ui_Favorite, 25);
  lv_obj_set_x                  (ui_Favorite, lv_pct(40));
  lv_obj_set_y                  (ui_Favorite, lv_pct(-44));
  lv_obj_set_align              (ui_Favorite, LV_ALIGN_CENTER);
  lv_obj_add_flag               (ui_Favorite, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

  lv_obj_set_style_bg_image_src (ui_Favorite, &ui_img_511832737,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_radius       (ui_Favorite, LV_RADIUS_CIRCLE,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_border_width (ui_Favorite, 0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left     (ui_Favorite, 8,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right    (ui_Favorite, 0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top      (ui_Favorite, 8,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom   (ui_Favorite, 0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

  lv_obj_set_style_bg_image_src (ui_Favorite, &ui_img_1050326551,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_color     (ui_Favorite, UI_COLOR_BACKGROUND,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_radius       (ui_Favorite, LV_RADIUS_CIRCLE,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_opa       (ui_Favorite, 255,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_left     (ui_Favorite,   8,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_right    (ui_Favorite,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_top      (ui_Favorite,   8,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_bottom   (ui_Favorite,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);

  lv_obj_t *ui_Repeat = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text                  (ui_Repeat, "");
  lv_obj_set_width                      (ui_Repeat, 25);
  lv_obj_set_height                     (ui_Repeat, 25);
  lv_obj_set_x                          (ui_Repeat, lv_pct(40));
  lv_obj_set_y                          (ui_Repeat, lv_pct(-15));
  lv_obj_set_align                      (ui_Repeat, LV_ALIGN_CENTER);
  lv_obj_add_flag                       (ui_Repeat, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

  lv_obj_set_style_bg_image_src         (ui_Repeat, &ui_img_repeat_png,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_recolor     (ui_Repeat, UI_COLOR_CHECKBOX,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_radius               (ui_Repeat,   5,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_opa         (ui_Repeat, 128,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_recolor_opa (ui_Repeat, 255,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_border_width         (ui_Repeat,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left             (ui_Repeat,   8,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right            (ui_Repeat,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top              (ui_Repeat,   8,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom           (ui_Repeat,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

  lv_obj_set_style_bg_image_src         (ui_Repeat, &ui_img_repeat_png,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_image_recolor     (ui_Repeat, UI_COLOR_BACKGROUND,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_image_opa         (ui_Repeat, 255,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_image_recolor_opa (ui_Repeat, 255,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);

  lv_obj_t *ui_Shuffle = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text                  (ui_Shuffle, "");
  lv_obj_set_width                      (ui_Shuffle, 25);
  lv_obj_set_height                     (ui_Shuffle, 25);
  lv_obj_set_x                          (ui_Shuffle, lv_pct(-40));
  lv_obj_set_y                          (ui_Shuffle, lv_pct(-15));
  lv_obj_set_align                      (ui_Shuffle, LV_ALIGN_CENTER);
  lv_obj_add_flag                       (ui_Shuffle, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

  lv_obj_set_style_bg_image_src         (ui_Shuffle, &ui_img_shuffle_png, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_recolor     (ui_Shuffle, UI_COLOR_CHECKBOX,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_radius               (ui_Shuffle, LV_RADIUS_CIRCLE,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_opa         (ui_Shuffle, 128,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_recolor_opa (ui_Shuffle, 255,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_border_width         (ui_Shuffle,   0,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left             (ui_Shuffle,   8,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right            (ui_Shuffle,   0,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top              (ui_Shuffle,   8,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom           (ui_Shuffle,   0,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

  lv_obj_set_style_bg_image_src         (ui_Shuffle, &ui_img_shuffle_png, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_image_recolor     (ui_Shuffle, UI_COLOR_BACKGROUND, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_image_opa         (ui_Shuffle, 255,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_image_recolor_opa (ui_Shuffle, 255,                 (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);

  ui_ButtonPlay = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text          (ui_ButtonPlay, "");
  lv_obj_set_width              (ui_ButtonPlay, 50);
  lv_obj_set_height             (ui_ButtonPlay, 50);
  lv_obj_set_x                  (ui_ButtonPlay, lv_pct(2));
  lv_obj_set_y                  (ui_ButtonPlay, lv_pct(27));
  lv_obj_set_align              (ui_ButtonPlay, LV_ALIGN_CENTER);
  lv_obj_add_flag               (ui_ButtonPlay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

  lv_obj_set_style_bg_image_src (ui_ButtonPlay, &ui_img_play_png,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_radius       (ui_ButtonPlay, LV_RADIUS_CIRCLE,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_border_width (ui_ButtonPlay,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left     (ui_ButtonPlay, 34,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right    (ui_ButtonPlay,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top      (ui_ButtonPlay, 34,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom   (ui_ButtonPlay,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

  lv_obj_set_style_bg_image_src (ui_ButtonPlay, &ui_img_pause_png,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_color     (ui_ButtonPlay, UI_COLOR_BACKGROUND,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_radius       (ui_ButtonPlay, LV_RADIUS_CIRCLE,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_opa       (ui_ButtonPlay, 255,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_border_width (ui_ButtonPlay,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_left     (ui_ButtonPlay,  34,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_right    (ui_ButtonPlay,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_top      (ui_ButtonPlay,  34,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_bottom   (ui_ButtonPlay,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);

  lv_obj_t *ui_ButtonNext = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text          (ui_ButtonNext, "");
  lv_obj_set_width              (ui_ButtonNext, 45);
  lv_obj_set_height             (ui_ButtonNext, 45);
  lv_obj_set_x                  (ui_ButtonNext, lv_pct(27));
  lv_obj_set_y                  (ui_ButtonNext, lv_pct(28));
  lv_obj_set_align              (ui_ButtonNext, LV_ALIGN_CENTER);
  lv_obj_add_flag               (ui_ButtonNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

  lv_obj_set_style_bg_image_src (ui_ButtonNext, &ui_img_715969206,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_radius       (ui_ButtonNext, LV_RADIUS_CIRCLE,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_border_width (ui_ButtonNext,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left     (ui_ButtonNext, 24,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right    (ui_ButtonNext,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top      (ui_ButtonNext, 24,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom   (ui_ButtonNext,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

  lv_obj_set_style_bg_image_src (ui_ButtonNext, &ui_img_715969206,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_color     (ui_ButtonNext, UI_COLOR_BACKGROUND,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_radius       (ui_ButtonNext, LV_RADIUS_CIRCLE,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_opa       (ui_ButtonNext, 255,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_border_width (ui_ButtonNext,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_left     (ui_ButtonNext,  24,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_right    (ui_ButtonNext,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_top      (ui_ButtonNext,  24,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_bottom   (ui_ButtonNext,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);

  lv_obj_set_style_bg_image_src (ui_ButtonNext, &ui_img_715969206,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_border_width (ui_ButtonNext,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_left     (ui_ButtonNext, 26,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_right    (ui_ButtonNext,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_top      (ui_ButtonNext, 26,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_bottom   (ui_ButtonNext,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);

  lv_obj_t *ui_ButtonPrev = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text          (ui_ButtonPrev, "");
  lv_obj_set_width              (ui_ButtonPrev, 45);
  lv_obj_set_height             (ui_ButtonPrev, 45);
  lv_obj_set_x                  (ui_ButtonPrev, lv_pct(-22));
  lv_obj_set_y                  (ui_ButtonPrev, lv_pct(28));
  lv_obj_set_align              (ui_ButtonPrev, LV_ALIGN_CENTER);
  lv_obj_add_flag               (ui_ButtonPrev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

  lv_obj_set_style_bg_image_src (ui_ButtonPrev, &ui_img_1076165770,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_radius       (ui_ButtonPrev, LV_RADIUS_CIRCLE,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_border_width (ui_ButtonPrev,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left     (ui_ButtonPrev, 24,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right    (ui_ButtonPrev,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top      (ui_ButtonPrev, 24,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom   (ui_ButtonPrev,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

  lv_obj_set_style_bg_image_src (ui_ButtonPrev, &ui_img_1076165770,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_color     (ui_ButtonPrev, UI_COLOR_BACKGROUND,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_radius       (ui_ButtonPrev, LV_RADIUS_CIRCLE,     (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_opa       (ui_ButtonPrev, 255,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_border_width (ui_ButtonPrev,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_left     (ui_ButtonPrev,  24,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_right    (ui_ButtonPrev,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_top      (ui_ButtonPrev,  24,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_bottom   (ui_ButtonPrev,   0,                  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);

  lv_obj_set_style_bg_image_src (ui_ButtonPrev, &ui_img_1076165770,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_border_width (ui_ButtonPrev,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_left     (ui_ButtonPrev, 26,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_right    (ui_ButtonPrev,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_top      (ui_ButtonPrev, 26,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_bottom   (ui_ButtonPrev,  0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);

  lv_obj_t *ui_VolumeMax = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text          (ui_VolumeMax, "");
  lv_obj_set_width              (ui_VolumeMax, 40);
  lv_obj_set_height             (ui_VolumeMax, 40);
  lv_obj_set_x                  (ui_VolumeMax, lv_pct(40));
  lv_obj_set_y                  (ui_VolumeMax, lv_pct(43));
  lv_obj_set_align              (ui_VolumeMax, LV_ALIGN_CENTER);
  lv_obj_add_flag               (ui_VolumeMax, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

  lv_obj_set_style_bg_image_src (ui_VolumeMax, &ui_img_1994412056,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_radius       (ui_VolumeMax, LV_RADIUS_CIRCLE,      (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_border_width (ui_VolumeMax,  0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left     (ui_VolumeMax, 22,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right    (ui_VolumeMax,  0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top      (ui_VolumeMax, 22,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom   (ui_VolumeMax,  0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

  lv_obj_set_style_bg_image_src (ui_VolumeMax, &ui_img_1994412056,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_color     (ui_VolumeMax, UI_COLOR_BACKGROUND,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_radius       (ui_VolumeMax, LV_RADIUS_CIRCLE,      (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_opa       (ui_VolumeMax, 255,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_left     (ui_VolumeMax,  22,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_right    (ui_VolumeMax,   0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_top      (ui_VolumeMax,  22,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_bottom   (ui_VolumeMax,   0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);

  lv_obj_set_style_bg_image_src (ui_VolumeMax, &ui_img_1994412056,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_left     (ui_VolumeMax, 24,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_right    (ui_VolumeMax,  0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_top      (ui_VolumeMax, 24,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_bottom   (ui_VolumeMax,  0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);

  lv_obj_t *ui_VolumeMin = lv_checkbox_create(ui_ScreenMain);
  lv_checkbox_set_text          (ui_VolumeMin, "");
  lv_obj_set_width              (ui_VolumeMin, 40);
  lv_obj_set_height             (ui_VolumeMin, 40);
  lv_obj_set_x                  (ui_VolumeMin, lv_pct(-39));
  lv_obj_set_y                  (ui_VolumeMin, lv_pct(43));
  lv_obj_set_align              (ui_VolumeMin, LV_ALIGN_CENTER);
  lv_obj_add_flag               (ui_VolumeMin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

  lv_obj_set_style_bg_image_src (ui_VolumeMin, &ui_img_2058316518,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_radius       (ui_VolumeMin, LV_RADIUS_CIRCLE,      (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_border_width (ui_VolumeMin,  0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left     (ui_VolumeMin, 22,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right    (ui_VolumeMin,  0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top      (ui_VolumeMin, 22,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom   (ui_VolumeMin,  0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

  lv_obj_set_style_bg_image_src (ui_VolumeMin, &ui_img_2058316518,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_color     (ui_VolumeMin, UI_COLOR_BACKGROUND,   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_radius       (ui_VolumeMin, LV_RADIUS_CIRCLE,      (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_opa       (ui_VolumeMin, 255,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_left     (ui_VolumeMin,  22,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_right    (ui_VolumeMin,   0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_top      (ui_VolumeMin,  22,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_pad_bottom   (ui_VolumeMin,   0,                   (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);

  lv_obj_set_style_bg_image_src (ui_VolumeMin, &ui_img_2058316518,    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_left     (ui_VolumeMin, 24,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_right    (ui_VolumeMin,  0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_top      (ui_VolumeMin, 24,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_pad_bottom   (ui_VolumeMin,  0,                    (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);

  ui_Volume = lv_slider_create(ui_ScreenMain);
  lv_slider_set_range           (ui_Volume, 0, 21); // MP3_VOLUME_MAX (21) is defined in CYD_MP3Player.h
  lv_slider_set_value           (ui_Volume, 0, LV_ANIM_OFF);
  lv_obj_set_height             (ui_Volume, 8);
  lv_obj_set_width              (ui_Volume, lv_pct(49));
  lv_obj_set_x                  (ui_Volume, lv_pct(1));
  lv_obj_set_y                  (ui_Volume, lv_pct(43));
  lv_obj_set_align              (ui_Volume, LV_ALIGN_CENTER);
  lv_obj_remove_flag            (ui_Volume, LV_OBJ_FLAG_GESTURE_BUBBLE);
  if (lv_slider_get_mode        (ui_Volume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Volume, 0, LV_ANIM_OFF);

  lv_obj_set_style_bg_color     (ui_Volume, UI_COLOR_SLIDER, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa       (ui_Volume, 255,             (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);

  lv_obj_set_style_bg_color     (ui_Volume, UI_COLOR_SLIDER, (uint32_t)LV_PART_KNOB | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa       (ui_Volume, 255,             (uint32_t)LV_PART_KNOB | (uint32_t)LV_STATE_DEFAULT);

  // Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
  if (lv_obj_get_style_pad_top  (ui_Volume, (uint32_t)LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Volume, lv_obj_get_style_pad_right(ui_Volume, (uint32_t)LV_PART_MAIN) + 1, (uint32_t)LV_PART_MAIN);

  lv_obj_add_event_cb(ui_MenuDotMain, ui_event_MenuDotMain, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Favorite,    ui_event_Favorite,    LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Repeat,      ui_event_Repeat,      LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Shuffle,     ui_event_Shuffle,     LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_ButtonPlay,  ui_event_ButtonPlay,  LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_ButtonNext,  ui_event_ButtonNext,  LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_ButtonPrev,  ui_event_ButtonPrev,  LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_VolumeMax,   ui_event_VolumeMax,   LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_VolumeMin,   ui_event_VolumeMin,   LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Volume,      ui_event_Volume,      LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_ElapsedBar,  ui_event_ElapsedBar,  LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_ScreenMain,  ui_event_ScreenMain,  LV_EVENT_ALL, NULL);
}