// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "../list.h"

#include "../CYD_MP3Player.h"
extern CYD_MP3Player *ui_get_player(void);  // Defined in ui.cpp

#define ALBUM_CELL_HEIGHT 32

static lv_obj_t *album_list;

/*--------------------------------------------------------------------------------
 *
 *--------------------------------------------------------------------------------*/
static void playlist_cb(lv_event_t *e) {
  DBG_ASSERT(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED);

  lv_obj_t * obj = lv_event_get_target_obj(e);
  ui_option.selectPlaylist = lv_dropdown_get_selected(obj);
}

/*--------------------------------------------------------------------------------
 * Set the pointer to the widget to NULL when its object is deleted
 *--------------------------------------------------------------------------------*/
static void delete_cb(lv_event_t *e) {
  lv_obj_t **obj = (lv_obj_t **)lv_event_get_user_data(e);
  static constexpr lv_obj_t ** const adrs[] = {
    &ui_ScreenAlbumList,
    &album_list,
  };

  for (int i = 0; i < sizeof(adrs) / sizeof(adrs[0]); i++) {
    if (obj == adrs[i]) {
      *obj = NULL;
      DBG_EXEC(printf("deleted: %d\n", i));
      return;
    }
  }
  DBG_EXEC(printf("deleted: 0x%x\n", obj));
}

/*--------------------------------------------------------------------------------
 * Initialize / Deinitialize widgets
 *--------------------------------------------------------------------------------*/
void ui_ScreenAlbumList_screen_init(void) {
  if (ui_ScreenAlbumList == NULL) {
    ui_ScreenAlbumList = lv_obj_create(NULL);
    lv_obj_set_style_bg_color     (ui_ScreenAlbumList, UI_COLOR_BACKGROUND, (uint32_t)LV_PART_MAIN | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_event_cb           (ui_ScreenAlbumList, ui_event_ScreenAlbumList, LV_EVENT_GESTURE, NULL);
    lv_obj_add_event_cb           (ui_ScreenAlbumList, ui_event_ScreenAlbumList, LV_EVENT_SCREEN_LOADED, NULL);
    lv_obj_add_event_cb           (ui_ScreenAlbumList, ui_event_ScreenAlbumList, LV_EVENT_SCREEN_UNLOADED, NULL);
    lv_obj_add_event_cb           (ui_ScreenAlbumList, delete_cb, LV_EVENT_DELETE, (void*)&ui_ScreenAlbumList);

    static constexpr lv_style_const_prop_t style_prop_common[] = {
      LV_STYLE_CONST_WIDTH(27),
      LV_STYLE_CONST_HEIGHT(27),
      LV_STYLE_CONST_X(LV_PCT_X(42)),
      LV_STYLE_CONST_Y(LV_PCT_Y(-44)),
      LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_default[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_menu_right),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
      LV_STYLE_CONST_BORDER_WIDTH(0),
      LV_STYLE_CONST_PAD_TOP(8),
      LV_STYLE_CONST_PAD_RIGHT(0),
      LV_STYLE_CONST_PAD_BOTTOM(0),
      LV_STYLE_CONST_PAD_LEFT(8),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_pressed[] = {
      LV_STYLE_CONST_PAD_TOP(10),
      LV_STYLE_CONST_PAD_LEFT(10),
      LV_STYLE_CONST_PROPS_END
    };
    static constexpr lv_style_const_prop_t style_prop_checked[] = {
      LV_STYLE_CONST_BG_IMAGE_SRC(&img_menu_right),
      LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_common,  (void*)style_prop_common );
    static LV_STYLE_CONST_INIT(style_default, (void*)style_prop_default);
    static LV_STYLE_CONST_INIT(style_pressed, (void*)style_prop_pressed);
    static LV_STYLE_CONST_INIT(style_checked, (void*)style_prop_checked);

    //////////////////// Back Icon ////////////////////
    lv_obj_t *obj = lv_checkbox_create(ui_ScreenAlbumList);
    lv_checkbox_set_text_static(obj, "");
    lv_obj_add_style    (obj, &style_common,  (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style    (obj, &style_default, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_add_style    (obj, &style_pressed, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
    lv_obj_add_style    (obj, &style_checked, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
    lv_obj_add_event_cb (obj, ui_event_AlbumToMainRight, LV_EVENT_CLICKED, NULL);

    //////////////////// Title Label ////////////////////
    obj = lv_label_create(ui_ScreenAlbumList);
    lv_obj_set_pos(obj, LV_PCT_X(5), LV_PCT_Y(4));
    lv_label_set_text_static(obj, "Album list");

    //////////////////// Dropdown List ////////////////////
    obj = lv_dropdown_create(ui_ScreenAlbumList);
    lv_obj_set_pos          (obj, LV_PCT_X(5), LV_PCT_Y(11));
    lv_obj_set_size         (obj, DROPDOWN_WIDTH, LV_SIZE_CONTENT);
    lv_obj_add_event_cb     (obj, playlist_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_dropdown_set_options (obj, "All");
    lv_dropdown_set_selected(obj, ui_option.selectPlaylist);

    //////////////////// List Container ////////////////////
    static constexpr lv_style_const_prop_t style_prop_album[] = {
      LV_STYLE_CONST_X(LV_PCT_X(5)),
      LV_STYLE_CONST_Y(LV_PCT_Y(26)),
      LV_STYLE_CONST_WIDTH(SCREEN_WIDTH - LV_PCT_X(10)),
      LV_STYLE_CONST_HEIGHT(ALBUM_CELL_HEIGHT * 7 - 4),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_album, (void*)style_prop_album);

    album_list = lv_list_create(ui_ScreenAlbumList);
    lv_obj_add_style    (album_list, &style_album, 0);
    lv_obj_add_event_cb (album_list, delete_cb, LV_EVENT_DELETE, (void*)&album_list);
  }
}

void ui_ScreenAlbumList_screen_deinit(void) {
  if (ui_ScreenAlbumList) {
    // Clear playlist before creating a new list
    CYD_MP3Player *player = ui_get_player();
    player->ClearPlayList();

    lv_obj_delete_async(ui_ScreenAlbumList);
  }
}

/*--------------------------------------------------------------------------------
 * Create selectable playlist
 *--------------------------------------------------------------------------------*/
void ui_ScreenAlbumList_create_list(const char *root_dir) {
  // Clear album list before creating a new list
  reset_cell_count(); // Defined in list.cpp

  // Create the album list from playlist
  CYD_MP3Player *player = ui_get_player();
  add_node_to_list(player->m_tree, album_list);
}