// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_ScreenPlayList_screen_init(void)
{
ui_ScreenPlayList = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScreenPlayList, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenPlayList, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenPlayList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuBackLeft = lv_checkbox_create(ui_ScreenPlayList);
lv_checkbox_set_text(ui_MenuBackLeft," ");
lv_obj_set_width( ui_MenuBackLeft, 27);
lv_obj_set_height( ui_MenuBackLeft, 27);
lv_obj_set_x( ui_MenuBackLeft, lv_pct(-40) );
lv_obj_set_y( ui_MenuBackLeft, lv_pct(-44) );
lv_obj_set_align( ui_MenuBackLeft, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuBackLeft, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

lv_obj_set_style_radius(ui_MenuBackLeft, 100, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_MenuBackLeft, &ui_img_713466046, LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(ui_MenuBackLeft, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MenuBackLeft, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MenuBackLeft, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MenuBackLeft, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MenuBackLeft, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_MenuBackLeft, 100, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_MenuBackLeft, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_MenuBackLeft, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_image_src( ui_MenuBackLeft, &ui_img_713466046, LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_radius(ui_MenuBackLeft, 100, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_bg_image_src( ui_MenuBackLeft, &ui_img_713466046, LV_PART_INDICATOR | LV_STATE_PRESSED );
lv_obj_set_style_border_width(ui_MenuBackLeft, 0, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_pad_left(ui_MenuBackLeft, 10, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_pad_right(ui_MenuBackLeft, 0, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_pad_top(ui_MenuBackLeft, 10, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_pad_bottom(ui_MenuBackLeft, 0, LV_PART_INDICATOR| LV_STATE_PRESSED);

ui_MenuBluetoothOn = lv_checkbox_create(ui_ScreenPlayList);
lv_checkbox_set_text(ui_MenuBluetoothOn," ");
lv_obj_set_width( ui_MenuBluetoothOn, 27);
lv_obj_set_height( ui_MenuBluetoothOn, 27);
lv_obj_set_x( ui_MenuBluetoothOn, lv_pct(40) );
lv_obj_set_y( ui_MenuBluetoothOn, lv_pct(-44) );
lv_obj_set_align( ui_MenuBluetoothOn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuBluetoothOn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

lv_obj_set_style_radius(ui_MenuBluetoothOn, 100, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_MenuBluetoothOn, &ui_img_1753861343, LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(ui_MenuBluetoothOn, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MenuBluetoothOn, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MenuBluetoothOn, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MenuBluetoothOn, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MenuBluetoothOn, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_MenuBluetoothOn, 100, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_MenuBluetoothOn, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_MenuBluetoothOn, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_image_src( ui_MenuBluetoothOn, &ui_img_1753861343, LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_radius(ui_MenuBluetoothOn, 100, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_bg_image_src( ui_MenuBluetoothOn, &ui_img_1753861343, LV_PART_INDICATOR | LV_STATE_PRESSED );
lv_obj_set_style_border_width(ui_MenuBluetoothOn, 0, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_pad_left(ui_MenuBluetoothOn, 10, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_pad_right(ui_MenuBluetoothOn, 0, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_pad_top(ui_MenuBluetoothOn, 10, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_pad_bottom(ui_MenuBluetoothOn, 0, LV_PART_INDICATOR| LV_STATE_PRESSED);

ui_MenuBluetoothOff = lv_checkbox_create(ui_ScreenPlayList);
lv_checkbox_set_text(ui_MenuBluetoothOff," ");
lv_obj_set_width( ui_MenuBluetoothOff, 27);
lv_obj_set_height( ui_MenuBluetoothOff, 27);
lv_obj_set_x( ui_MenuBluetoothOff, lv_pct(20) );
lv_obj_set_y( ui_MenuBluetoothOff, lv_pct(-44) );
lv_obj_set_align( ui_MenuBluetoothOff, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuBluetoothOff, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

lv_obj_set_style_radius(ui_MenuBluetoothOff, 100, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_MenuBluetoothOff, &ui_img_1837194583, LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(ui_MenuBluetoothOff, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MenuBluetoothOff, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MenuBluetoothOff, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MenuBluetoothOff, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MenuBluetoothOff, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_MenuBluetoothOff, 100, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_MenuBluetoothOff, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_MenuBluetoothOff, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_image_src( ui_MenuBluetoothOff, &ui_img_1837194583, LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_radius(ui_MenuBluetoothOff, 100, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_bg_image_src( ui_MenuBluetoothOff, &ui_img_1837194583, LV_PART_INDICATOR | LV_STATE_PRESSED );
lv_obj_set_style_border_width(ui_MenuBluetoothOff, 0, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_pad_left(ui_MenuBluetoothOff, 10, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_pad_right(ui_MenuBluetoothOff, 0, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_pad_top(ui_MenuBluetoothOff, 10, LV_PART_INDICATOR| LV_STATE_PRESSED);
lv_obj_set_style_pad_bottom(ui_MenuBluetoothOff, 0, LV_PART_INDICATOR| LV_STATE_PRESSED);

lv_obj_add_event_cb(ui_MenuBackLeft, ui_event_MenuBackLeft, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MenuBluetoothOn, ui_event_MenuBluetoothOn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MenuBluetoothOff, ui_event_MenuBluetoothOff, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenPlayList, ui_event_ScreenPlayList, LV_EVENT_ALL, NULL);

}
