// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

#include "../CYD_MP3Player.h"
extern void ui_get_id3tags(uint32_t track_id, ID3Tags_t &tags); // Defined in ui.cpp

/**********************
 *      MACROS
 **********************/
#define LIST_FONT_SMALL_HEIGHT    17  // For font size: 12px
#define LIST_FONT_MEDIUM_HEIGHT   22  // For font size: 14px
#define LIST_LABEL_MARGINE        100 // left(50) + right(50)
#define LIST_CELL_HEIGHT          54  // Inside a cell = column(3) x rol(2)
#define LIST_CELL_VIEWS           6   // LIST_CELL_HEIGHT * LIST_CELL_VIEWS >= SCREEN_HEIGHT
#define LIST_CELL_SPARE           2   // 1 <= LIST_CELL_SPARE <= 2

/**********************
 *  STATIC VARIABLES
 **********************/
static lv_obj_t *play_list;
static lv_obj_t *slider;
static bool update_scroll_running = false;

static lv_style_t style_grid;
static constexpr lv_style_const_prop_t style_cell_prop[] = {
  LV_STYLE_CONST_BG_OPA(LV_OPA_TRANSP),
  LV_STYLE_CONST_LAYOUT(LV_LAYOUT_GRID),
  LV_STYLE_CONST_PAD_RIGHT(20),
  LV_STYLE_CONST_PROPS_END
};
static constexpr lv_style_const_prop_t style_cell_pressed_prop[] = {
  LV_STYLE_CONST_BG_OPA(LV_OPA_COVER),
  LV_STYLE_CONST_BG_COLOR(UI_COLOR_LIST_DEFAULT),
  LV_STYLE_CONST_PROPS_END
};
static constexpr lv_style_const_prop_t style_cell_checked_prop[] = {
  LV_STYLE_CONST_BG_OPA(LV_OPA_COVER),
  LV_STYLE_CONST_BG_COLOR(UI_COLOR_LIST_DEFAULT),
  LV_STYLE_CONST_PROPS_END
};
static constexpr lv_style_const_prop_t style_title_prop[] = {
  LV_STYLE_CONST_WIDTH(SCREEN_WIDTH - LIST_LABEL_MARGINE),
  LV_STYLE_CONST_HEIGHT(LIST_FONT_MEDIUM_HEIGHT),
  LV_STYLE_CONST_TEXT_FONT(&CUSTOM_FONT_MEDIUM),
  LV_STYLE_CONST_TEXT_COLOR(UI_COLOR_BACKGROUND),
  LV_STYLE_CONST_PROPS_END
};
static constexpr lv_style_const_prop_t style_artist_prop[] = {
  LV_STYLE_CONST_WIDTH(SCREEN_WIDTH - LIST_LABEL_MARGINE),
  LV_STYLE_CONST_HEIGHT(LIST_FONT_SMALL_HEIGHT),
  LV_STYLE_CONST_PAD_RIGHT(5),
  LV_STYLE_CONST_TEXT_FONT(&CUSTOM_FONT_SMALL),
  LV_STYLE_CONST_TEXT_COLOR(UI_COLOR_LIST_ARTIST),
  LV_STYLE_CONST_PROPS_END
};
static constexpr lv_style_const_prop_t style_time_prop[] = {
  LV_STYLE_CONST_TEXT_FONT(&CUSTOM_FONT_SMALL),
  LV_STYLE_CONST_TEXT_COLOR(UI_COLOR_BACKGROUND),
  LV_STYLE_CONST_PROPS_END
};
static constexpr lv_style_const_prop_t style_heart_prop[] = {
  LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
  LV_STYLE_CONST_BG_OPA(0),
  LV_STYLE_CONST_BORDER_WIDTH(0),
  LV_STYLE_CONST_PAD_LEFT(-5), // slightly offset to the right
  LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
  LV_STYLE_CONST_PROPS_END
};
static constexpr lv_style_const_prop_t style_menu_back_prop[] = {
  LV_STYLE_CONST_BG_COLOR(UI_COLOR_LIST_DEFAULT),
  LV_STYLE_CONST_SHADOW_COLOR(UI_COLOR_LIST_SHADOW),
  LV_STYLE_CONST_BG_OPA(255),
  LV_STYLE_CONST_BORDER_WIDTH(0),
  LV_STYLE_CONST_SHADOW_OPA(255),
  LV_STYLE_CONST_SHADOW_WIDTH(1),
  LV_STYLE_CONST_SHADOW_SPREAD(0),
  LV_STYLE_CONST_SHADOW_OFFSET_X(0),
  LV_STYLE_CONST_PAD_TOP(8),
  LV_STYLE_CONST_PAD_RIGHT(0),
  LV_STYLE_CONST_PAD_BOTTOM(0),
  LV_STYLE_CONST_PAD_LEFT(249),
  LV_STYLE_CONST_PROPS_END
};
static LV_STYLE_CONST_INIT(style_cell,          (void*)style_cell_prop);
static LV_STYLE_CONST_INIT(style_cell_pressed,  (void*)style_cell_pressed_prop);
static LV_STYLE_CONST_INIT(style_cell_checked,  (void*)style_cell_checked_prop);
static LV_STYLE_CONST_INIT(style_title,         (void*)style_title_prop);
static LV_STYLE_CONST_INIT(style_artist,        (void*)style_artist_prop);
static LV_STYLE_CONST_INIT(style_time,          (void*)style_time_prop);
static LV_STYLE_CONST_INIT(style_heart,         (void*)style_heart_prop);
static LV_STYLE_CONST_INIT(style_menu_back,     (void*)style_menu_back_prop);

/**********************
 *  GLOBAL FUNCTIONS
 **********************/
void ui_list_update_icon(uint32_t track_id, bool state) {
  if (play_list && (ui_control.top <= track_id && track_id <= ui_control.end)) {
    lv_obj_t* cell = lv_obj_get_child(play_list, track_id - ui_control.top);
    if (cell) {
      lv_obj_t* icon = lv_obj_get_child(cell, 0);
      if (state) {
        lv_image_set_src(icon, &img_list_pause);
      } else {
        lv_image_set_src(icon, &img_list_play);
      }
    }
  }
}

void ui_list_update_cell(uint32_t track_id, bool state) {
  if (play_list && (ui_control.top <= track_id && track_id <= ui_control.end)) {
    lv_obj_t* cell = lv_obj_get_child(play_list, track_id - ui_control.top);
    if (cell) {
      lv_obj_t* title  = lv_obj_get_child(cell, 1);
      lv_obj_t* artist = lv_obj_get_child(cell, 2);

      if (state) {
        lv_label_set_long_mode(title,  LV_LABEL_LONG_SCROLL_CIRCULAR);
        lv_label_set_long_mode(artist, LV_LABEL_LONG_SCROLL_CIRCULAR);
        lv_obj_add_state(cell, LV_STATE_CHECKED);
      } else {
        lv_label_set_long_mode(title,  LV_LABEL_LONG_DOT);
        lv_label_set_long_mode(artist, LV_LABEL_LONG_DOT);
        lv_obj_remove_state(cell, LV_STATE_CHECKED);
      }
    }
  }
}

void ui_list_update_play(uint32_t track_id, bool state) {
  if (play_list && (ui_control.top <= track_id && track_id <= ui_control.end)) {
    lv_obj_t* cell = lv_obj_get_child(play_list, track_id - ui_control.top);
    if (cell) {
      lv_obj_t* icon   = lv_obj_get_child(cell, 0);
      lv_obj_t* title  = lv_obj_get_child(cell, 1);
      lv_obj_t* artist = lv_obj_get_child(cell, 2);

      if (state) {
        lv_image_set_src(icon, &img_list_pause);
        lv_label_set_long_mode(title,  LV_LABEL_LONG_SCROLL_CIRCULAR);
        lv_label_set_long_mode(artist, LV_LABEL_LONG_SCROLL_CIRCULAR);
        lv_obj_add_state(cell, LV_STATE_CHECKED);
        lv_obj_scroll_to_view(cell, LV_ANIM_ON);
      } else {
        lv_image_set_src(icon, &img_list_play);
        lv_label_set_long_mode(title,  LV_LABEL_LONG_DOT);
        lv_label_set_long_mode(artist, LV_LABEL_LONG_DOT);
        lv_obj_remove_state(cell, LV_STATE_CHECKED);
      }
    }
  }
}

/**********************
 *   STATIC FUNCTIONS
 **********************/
static void list_click_event_cb(lv_event_t* e) {
  uint32_t track_id = (uint32_t)lv_event_get_user_data(e);

  lv_point_t p;
  lv_indev_get_point(lv_indev_get_act(), &p);

  // If the clicked coordinates within the icon area...
  if (p.x <= img_list_play.header.w) {
    // If currently playing...
    if (ui_control.playNo == track_id) {
      // Execute pause/resume
      ui_state = (ui_state == UI_STATE_PLAY ? UI_STATE_PAUSE : UI_STATE_RESUME);
      lv_obj_set_state(ui_ButtonPlay, LV_STATE_CHECKED, ui_state == UI_STATE_PAUSE ? false : true);
    }
    // Else select the new track to play
    else {
      ui_list_update_play(ui_control.playNo,  false);
      ui_list_update_cell(ui_control.focusNo, false);
      ui_list_update_play(track_id, true);
      ui_set_playNo(track_id);
    }
  }
  // Else just change the focused cell
  else {
    ui_list_update_cell(ui_control.focusNo, false);
    ui_control.focusNo = track_id;
    ui_list_update_cell(track_id, true);
  }
}

static lv_obj_t *add_list_cell(lv_obj_t* parent, uint32_t track_id) {
  ID3Tags_t tags;
  ui_get_id3tags(track_id, tags);

  lv_obj_t* cell = lv_obj_create(parent);
  lv_obj_remove_style_all       (cell);
  lv_obj_set_size               (cell, lv_pct(100), LIST_CELL_HEIGHT);

  lv_obj_add_style              (cell, &style_grid, 0);
  lv_obj_add_style              (cell, &style_cell, 0);
  lv_obj_add_style              (cell, &style_cell_pressed, LV_STATE_PRESSED);
  lv_obj_add_style              (cell, &style_cell_checked, LV_STATE_CHECKED);
  lv_obj_add_event_cb           (cell, list_click_event_cb, LV_EVENT_CLICKED, (void*)track_id);
  lv_obj_remove_flag            (cell, LV_OBJ_FLAG_SCROLLABLE); // Stop sliding horizontally

  //////////////////// Play Button ////////////////////
  lv_obj_t* obj = lv_image_create(cell);
  lv_image_set_src              (obj, &img_list_play);
  lv_obj_set_grid_cell          (obj, LV_GRID_ALIGN_START, 0, 1, LV_GRID_ALIGN_CENTER, 0, 2);

  //////////////////// Title Label ////////////////////
  obj = lv_label_create(cell);
  lv_label_set_text             (obj, tags.title.c_str());
  lv_label_set_long_mode        (obj, LV_LABEL_LONG_DOT);
  lv_obj_set_grid_cell          (obj, LV_GRID_ALIGN_START, 1, 1, LV_GRID_ALIGN_CENTER, 0, 1);
  lv_obj_add_style              (obj, &style_title, 0);

  //////////////////// Artist Label ////////////////////
  obj = lv_label_create(cell);
  lv_label_set_text_fmt         (obj, "%s / %s", tags.artist.c_str(), tags.album.c_str());
  lv_label_set_long_mode        (obj, LV_LABEL_LONG_DOT);
  lv_obj_set_grid_cell          (obj, LV_GRID_ALIGN_START, 1, 1, LV_GRID_ALIGN_CENTER, 1, 1);
  lv_obj_add_style              (obj, &style_artist, 0);

  //////////////////// Time Label ////////////////////
  obj = lv_label_create(cell);
  lv_label_set_text_fmt         (obj, "%" LV_PRIu32 ":%02" LV_PRIu32, tags.meta.duration / 60UL, tags.meta.duration % 60UL);
  lv_obj_set_grid_cell          (obj, LV_GRID_ALIGN_END, 2, 1, LV_GRID_ALIGN_END, 0, 2);
  lv_obj_add_style              (obj, &style_time, 0);

  //////////////////// Heart Checkbox ////////////////////
  obj = lv_checkbox_create(cell);
  lv_checkbox_set_text_static   (obj, "");
  lv_obj_set_state              (obj, LV_STATE_CHECKED, tags.meta.selected);
  lv_obj_set_grid_cell          (obj, LV_GRID_ALIGN_END, 2, 1, LV_GRID_ALIGN_START, 0, 2);
  lv_obj_add_event_cb           (obj, ui_event_PlayList_Heart, LV_EVENT_CLICKED, (void*)track_id);
  lv_obj_add_style              (obj, &style_heart,         (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_add_style              (obj, &style_heart,         (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_add_style              (obj, &style_heart,         (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
  lv_obj_set_style_bg_image_src (obj, &img_heart_off_small, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_src (obj, &img_heart_on_small,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
  lv_obj_set_style_bg_image_src (obj, &img_heart_off_small, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);

  //////////////////// Border Image ////////////////////
  obj = lv_image_create(cell);
  lv_image_set_src              (obj, &img_lv_demo_music_list_border);
  lv_image_set_inner_align      (obj, LV_IMAGE_ALIGN_TILE);
  lv_obj_set_width              (obj, lv_pct(120));
  lv_obj_align                  (obj, LV_ALIGN_BOTTOM_MID, 0, 0);
  lv_obj_add_flag               (obj, LV_OBJ_FLAG_IGNORE_LAYOUT);

  return cell;
}

static void update_scroll(lv_obj_t *obj) {
  // Do not re-enter this function when `lv_obj_scroll_by` triggers this callback again.
  if (update_scroll_running) return;
  update_scroll_running = true;

  int32_t pos;

  /* Load items we're getting close to */
  while (ui_control.end < ui_get_counts() - 1 && (pos = lv_obj_get_scroll_bottom(obj)) < (LIST_CELL_HEIGHT)) {
    ui_control.end += 1;
    add_list_cell(obj, ui_control.end);
    lv_obj_update_layout(obj);
    //DBG_EXEC(printf("added ui_control.end: %d, pos: %d\n", ui_control.end, pos));
  }
  while (ui_control.top > 0 && (pos = lv_obj_get_scroll_top(obj)) < (LIST_CELL_HEIGHT)) {
    ui_control.top -= 1;
    int32_t bottom_before = lv_obj_get_scroll_bottom(obj);
    lv_obj_t *new_item = add_list_cell(obj, ui_control.top);
    lv_obj_move_to_index(new_item, 0);
    lv_obj_update_layout(obj);
    int32_t bottom_after = lv_obj_get_scroll_bottom(obj);
    lv_obj_scroll_by(obj, 0, bottom_before - bottom_after, LV_ANIM_OFF);
    //DBG_EXEC(printf("added ui_control.top: %d, pos: %d\n", ui_control.top, pos));
  }

  /* Delete far-away items */
  while ((pos = lv_obj_get_scroll_bottom(obj)) > (LIST_CELL_HEIGHT * LIST_CELL_SPARE) && ui_control.end - ui_control.top > (LIST_CELL_VIEWS)) {
    ui_control.end -= 1;
    lv_obj_t *child = lv_obj_get_child(obj, -1);
    lv_obj_delete(child);
    lv_obj_update_layout(obj);
    //DBG_EXEC(printf("deleted ui_control.end: %d, pos: %d\n", ui_control.end, pos));
  }
  while ((pos = lv_obj_get_scroll_top(obj)) > (LIST_CELL_HEIGHT * LIST_CELL_SPARE) && ui_control.end - ui_control.top > (LIST_CELL_VIEWS)) {
    ui_control.top += 1;
    int32_t bottom_before = lv_obj_get_scroll_bottom(obj);
    lv_obj_t *child = lv_obj_get_child(obj, 0);
    lv_obj_delete(child);
    lv_obj_update_layout(obj);
    int32_t bottom_after = lv_obj_get_scroll_bottom(obj);
    lv_obj_scroll_by(obj, 0, bottom_before - bottom_after, LV_ANIM_OFF);
    //DBG_EXEC(printf("deleted ui_control.top: %d, pos: %d\n", ui_control.top, pos));
  }

  update_scroll_running = false;
  ui_list_update_cell(ui_control.focusNo, true);
  ui_list_update_icon(ui_get_playNo(),    true);

  // Update slider
  int32_t top = lv_obj_get_scroll_top(obj) + ui_control.top * LIST_CELL_HEIGHT;
  int32_t end = top + LIST_CELL_VIEWS * LIST_CELL_HEIGHT;
  lv_slider_set_value     (slider, end, LV_ANIM_OFF);
  lv_slider_set_left_value(slider, top, LV_ANIM_OFF);
}

static void scroll_cb(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  if (event_code == LV_EVENT_SCROLL) {
    // lv_obj_t *obj = lv_event_get_target_obj(e);
    // assert(obj == play_list);
    update_scroll(play_list);
  }
}

/*--------------------------------------------------------------------------------
 * Initialize the style of each cell in the playlist
 *--------------------------------------------------------------------------------*/
static void ui_ScreenPlayList_list_init(lv_obj_t* parent) {
  static const lv_coord_t grid_cols[] = { LV_GRID_CONTENT, LV_GRID_FR(1), (int32_t)img_heart_off_small.header.w, LV_GRID_TEMPLATE_LAST };
  static const lv_coord_t grid_rows[] = { LIST_FONT_MEDIUM_HEIGHT, LIST_FONT_SMALL_HEIGHT, LV_GRID_TEMPLATE_LAST };

  lv_style_init                     (&style_grid);
  lv_style_set_grid_column_dsc_array(&style_grid, grid_cols);
  lv_style_set_grid_row_dsc_array   (&style_grid, grid_rows);
  lv_style_set_grid_row_align       (&style_grid, LV_GRID_ALIGN_CENTER);

  // Create an empty transparent container
  if (play_list == NULL) {
    play_list = lv_obj_create(parent);
    lv_obj_remove_style_all         (play_list);
    lv_obj_set_size                 (play_list, lv_pct(100), lv_pct(100));
    lv_obj_set_align                (play_list, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow            (play_list, LV_FLEX_FLOW_COLUMN);
    lv_obj_add_event_cb             (play_list, scroll_cb, LV_EVENT_SCROLL, NULL);
  }

  // Creating a slider as an alternative to a scrollbar
  if (slider == NULL) {
    slider = lv_slider_create(parent);
    lv_obj_align                    (slider, LV_ALIGN_TOP_RIGHT, -2, 0);
    lv_obj_remove_flag              (slider, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_size                 (slider, 4, LIST_CELL_VIEWS * LIST_CELL_HEIGHT);
    lv_obj_set_style_radius         (slider, LV_RADIUS_CIRCLE,      (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa         (slider, 0, /* set invisible */ (uint32_t)LV_PART_KNOB      | (uint32_t)LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color       (slider, UI_COLOR_LIST_SLIDER,  (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
    lv_slider_set_mode              (slider, LV_SLIDER_MODE_RANGE);
    lv_slider_set_range             (slider, ui_get_counts() * LIST_CELL_HEIGHT, 0);
  }
}

/*--------------------------------------------------------------------------------
 * Delete all cells in the list
 *--------------------------------------------------------------------------------*/
static void ui_list_remove_all(void) {
  while (lv_obj_get_child_count(play_list)) {
    lv_obj_clean(play_list);
  }
}

/*--------------------------------------------------------------------------------
 * Create cells from top to end in the list
 *--------------------------------------------------------------------------------*/
static void ui_list_create_all(void) {
  // Update layout before add new cells
  lv_slider_set_value     (slider, 0, LV_ANIM_OFF);
  lv_slider_set_left_value(slider, 0, LV_ANIM_OFF);
  lv_obj_update_layout    (slider);
  lv_obj_update_layout    (play_list);

  add_list_cell(play_list, ui_control.top);
  update_scroll(play_list);
  ui_list_update_cell(ui_control.focusNo, true);
}

/*--------------------------------------------------------------------------------
 * Focus the specified cell when it is out of range
 *--------------------------------------------------------------------------------*/
void ui_list_focus_playing(uint32_t track_id) {
  if (play_list && (track_id < ui_control.top || ui_control.end < track_id)) {
    // Delete all cells in playlist
    ui_list_remove_all();

    // Add new cells according to the specified id
    ui_control.focusNo = ui_control.top = ui_control.end = track_id;
    ui_list_create_all();
  }
}

/*--------------------------------------------------------------------------------
 * Updates the duration to the specified cell
 *--------------------------------------------------------------------------------*/
void ui_list_update_duration(uint32_t track_id, uint32_t duration) {
  if (play_list && (ui_control.top <= track_id && track_id <= ui_control.end)) {
    lv_obj_t* cell = lv_obj_get_child(play_list, track_id - ui_control.top);
    if (cell) {
      lv_obj_t* time_label = lv_obj_get_child(cell, 3);
      lv_label_set_text_fmt(time_label, "%" LV_PRIu32 ":%02" LV_PRIu32, duration / 60, duration % 60);
    }
  }
}

/*--------------------------------------------------------------------------------
 * Set the pointer to the widget to NULL when its object is deleted
 *--------------------------------------------------------------------------------*/
static void delete_cb(lv_event_t *e) {
  lv_obj_t **obj = (lv_obj_t **)lv_event_get_user_data(e);
  static constexpr lv_obj_t ** const adrs[] = {
    &ui_ScreenPlayList,
    &play_list,
    &slider,
  };

  for (int i = 0; i < sizeof(adrs) / sizeof(adrs[0]); i++) {
    if (obj == adrs[i]) {
      *obj = NULL;
      DBG_EXEC(printf("deleted: %d\n", i));
      return;
    }
  }
  DBG_EXEC(printf("deleted: 0x%x\n", obj));
}

/*--------------------------------------------------------------------------------
 * This initialization is executed once
 *--------------------------------------------------------------------------------*/
void ui_ScreenPlayList_screen_init(void) {
  if (ui_ScreenPlayList == NULL) {
    ui_ScreenPlayList = lv_obj_create(NULL);
    lv_obj_remove_flag        (ui_ScreenPlayList, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color (ui_ScreenPlayList, UI_COLOR_LIST_PRESSED, 0);
    lv_obj_set_style_bg_opa   (ui_ScreenPlayList, 255,                   0);
  }

  lv_obj_t *container = lv_obj_create(ui_ScreenPlayList);
  lv_obj_remove_style_all (container);
  lv_obj_set_size         (container, lv_pct(100), lv_pct(100));
  lv_obj_set_align        (container, LV_ALIGN_TOP_MID);
  lv_obj_remove_flag      (container, (lv_obj_flag_t)(LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE));

  lv_obj_add_event_cb(ui_ScreenPlayList, ui_event_PlayListToMain, LV_EVENT_GESTURE, NULL);
  lv_obj_add_event_cb(ui_ScreenPlayList, ui_event_ScreenPlayList, LV_EVENT_SCREEN_UNLOADED, NULL);

  // Initialize play list container
  ui_ScreenPlayList_list_init(container);

  // Add a callback when an object is deleted
  lv_obj_add_event_cb(ui_ScreenPlayList,  delete_cb, LV_EVENT_DELETE, (void*)&ui_ScreenPlayList);
  lv_obj_add_event_cb(play_list,          delete_cb, LV_EVENT_DELETE, (void*)&play_list);
  lv_obj_add_event_cb(slider,             delete_cb, LV_EVENT_DELETE, (void*)&slider);

  // Add new cells according to the specified id
  ui_control.top = ui_control.end = ui_control.playNo;
  ui_list_create_all();
}

void ui_ScreenPlayList_screen_deinit(void) {
  if (ui_ScreenPlayList) {
    lv_style_reset(&style_grid);
    lv_obj_delete_async(ui_ScreenPlayList);
  }
}