// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "../tree.hpp"
#include <string.h>

#include "../CYD_MP3Player.h"
extern CYD_MP3Player *ui_get_player(void);  // Defined in ui.cpp

// List Components
#define CELL_HEIGHT_SMALL   31  // for CUSTOM_FONT_SMALL
#define CELL_HEIGHT_MEDIUM  34  // for CUSTOM_FONT_MEDIUM
#define CELL_OFFSET_NODE    6   // offset for node text
#define CELL_OFFSET_LEAF    10  // offset for leaf text
#define CELL_PADDING_LEFT   6   // padding left in pixels
#define CELL_PADDING_BORDER 8   // padding top/bottom in pixels
#define FOLDING_DURATION    250 // folding animation duration
#define MAX_CELLS           100 // LV_MEM_SIZE = (64 * 1024U)
#define ALBUM_CELL_HEIGHT   32  // height of cell in album list
#define ALBUM_CELL_COUNTS   7   // number of cell views

#define CELL_COLOR_NODE     lv_color_hex(0xf4f4f4)
#define CELL_COLOR_LEAF     lv_color_hex(0xffffff)
#define CELL_COLOR_OUTLINE  { .blue = 0xe4, .green = 0xe0, .red = 0xe4 }  // lv_color_hex(0xe4e0e4)

static lv_obj_t *album_list;
static int cell_count;

//--------------------------------------------------------------------------------
//
//--------------------------------------------------------------------------------
static size_t get_cell_count(void) {
  return cell_count;
}

static void reset_cell_count(void) {
  cell_count = 0;
}

//--------------------------------------------------------------------------------
//
//--------------------------------------------------------------------------------
static lv_obj_t *get_parent(lv_obj_t *cell) {
  Node *node = (Node*)lv_obj_get_user_data(cell);

  while (cell = lv_obj_get_sibling(cell, -1)) {
    Node *n = (Node*)lv_obj_get_user_data(cell);
    if (n->meta.depth < node->meta.depth) {
      return cell;
    }
  }

  return NULL; // never reached
}

//--------------------------------------------------------------------------------
//
//--------------------------------------------------------------------------------
static NodeMeta_t *get_node_meta(lv_obj_t *cell) {
  Node *node = (Node*)lv_obj_get_user_data(cell);
  return &node->meta;
}

//--------------------------------------------------------------------------------
// https://docs.lvgl.io/master/details/widgets/table.html
//--------------------------------------------------------------------------------
static void draw_image_cb(lv_event_t *e) {
  // If the cells are drawn...
  lv_draw_task_t *draw_task = lv_event_get_draw_task(e);
  lv_draw_task_type_t type  = lv_draw_task_get_type(draw_task);

  if (type == LV_DRAW_TASK_TYPE_FILL) {
    lv_obj_t *cell = lv_event_get_target_obj(e);
    NodeMeta_t *meta = get_node_meta(cell);
    if (meta->depth > 1 && meta->hidden) {
      return;
    }

    // Draw icon image
    const lv_image_dsc_t *img;
    if (meta->type == TYPE_NODE) {
      img = (const lv_image_dsc_t*)(meta->checked ? &img_symbol_right : &img_symbol_down);
    } else {
      img = (const lv_image_dsc_t*)(meta->checked ? &img_checked : &img_checkbox);
    }

    lv_area_t area;
    area.x1 = 0;
    area.x2 = img->header.w - 1;
    area.y1 = 0;
    area.y2 = img->header.h - 1;
    lv_area_t draw_task_area;
    lv_draw_task_get_area(draw_task, &draw_task_area);
    lv_area_align(&draw_task_area, &area, LV_ALIGN_LEFT_MID, meta->depth * CELL_PADDING_LEFT, 0);

    lv_draw_dsc_base_t *base_dsc = (lv_draw_dsc_base_t *)lv_draw_task_get_draw_dsc(draw_task);

#if 1
    lv_draw_rect_dsc_t rect_dsc;
    lv_draw_rect_dsc_init(&rect_dsc);
    rect_dsc.bg_image_src = (const void *)img;
    rect_dsc.bg_color = meta->type == TYPE_NODE ? CELL_COLOR_NODE : CELL_COLOR_LEAF;
    lv_draw_rect(base_dsc->layer, &rect_dsc, &area);
#else
    lv_draw_image_dsc_t img_dsc;
    lv_draw_image_dsc_init(&img_dsc);
    img_dsc.src = (const void *)img;
    img_dsc.recolor = lv_color_black();
    lv_draw_image(base_dsc->layer, &img_dsc, &area);
#endif
  }
}

//--------------------------------------------------------------------------------
//
//--------------------------------------------------------------------------------
static void event_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);

  if (code == LV_EVENT_CLICKED) {
    lv_obj_t *cell = lv_event_get_target_obj(e);
    NodeMeta_t *meta = get_node_meta(cell);

    if (meta->type == TYPE_NODE) {
      uint8_t depth = meta->depth;
      bool checked  = meta->checked = !meta->checked;
      lv_obj_send_event(cell, LV_EVENT_STYLE_CHANGED, NULL);

      lv_anim_t a;
      lv_anim_init(&a);
      lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_height);
      lv_anim_set_duration(&a, FOLDING_DURATION);

      if (checked) {
        lv_anim_set_values(&a, CELL_HEIGHT_SMALL, 0);
      } else {
        lv_anim_set_values(&a, 0, CELL_HEIGHT_SMALL);
      }

      // folding with animation
      while (cell = lv_obj_get_sibling(cell, 1)) {
        meta = get_node_meta(cell);
        if (meta->depth <= depth) {
          break;
        }

        // RULE 1: child inherits the state of parent
        lv_obj_t *obj = get_parent(cell);
        NodeMeta_t *m = get_node_meta(obj);

        // RULE 2: child follows the state of parents
        bool hidden = checked | m->checked;
        if (meta->hidden == hidden) {
          continue;
        } else {
          meta->hidden = hidden;
        }

        lv_obj_send_event(cell, LV_EVENT_STYLE_CHANGED, NULL);
        lv_anim_set_var(&a, cell);
        lv_anim_start(&a);
      }
    }

    // change the state of checkbox
    else {
      meta->checked = !meta->checked;
      lv_obj_send_event(cell, LV_EVENT_STYLE_CHANGED, NULL);
    }
  }
}

//--------------------------------------------------------------------------------
//
//--------------------------------------------------------------------------------
static void set_styles(lv_obj_t *cell, Node *node) {
  static constexpr lv_style_const_prop_t style_prop_common[] = {
    LV_STYLE_CONST_ALIGN(LV_ALIGN_LEFT_MID),
    LV_STYLE_CONST_TEXT_FONT(&CUSTOM_FONT_SMALL),
//  LV_STYLE_CONST_HEIGHT(CELL_HEIGHT_SMALL),
    LV_STYLE_CONST_PAD_TOP(CELL_PADDING_BORDER),
    LV_STYLE_CONST_PAD_BOTTOM(CELL_PADDING_BORDER),
    LV_STYLE_CONST_OUTLINE_COLOR(CELL_COLOR_OUTLINE),
    LV_STYLE_CONST_OUTLINE_WIDTH(1),
    LV_STYLE_CONST_PROPS_END
  };
  static LV_STYLE_CONST_INIT(style_common, (void*)style_prop_common);
  lv_obj_add_style(cell, &style_common, (uint32_t)LV_PART_MAIN);

  NodeMeta_t *meta = &node->meta;
  lv_obj_set_style_height   (cell, (meta->depth > 1 && meta->hidden ? 0 : CELL_HEIGHT_SMALL), LV_PART_MAIN);
  lv_obj_set_style_bg_color (cell, (meta->type == TYPE_NODE ? CELL_COLOR_NODE : CELL_COLOR_LEAF), LV_PART_MAIN);
  lv_obj_set_style_pad_left (cell, (meta->type == TYPE_NODE ? CELL_OFFSET_NODE: CELL_OFFSET_LEAF) + meta->depth * CELL_PADDING_LEFT, LV_PART_MAIN);
  lv_label_set_long_mode    (cell, LV_LABEL_LONG_CLIP); // LV_LABEL_LONG_DOT, LV_LABEL_LONG_SCROLL_CIRCULAR

  lv_obj_set_user_data(cell, (void*)node);
  lv_obj_add_flag(cell, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_add_flag(cell, LV_OBJ_FLAG_SEND_DRAW_TASK_EVENTS);
  lv_obj_add_event_cb(cell, draw_image_cb, LV_EVENT_DRAW_TASK_ADDED, NULL);
  lv_obj_add_event_cb(cell, event_handler, LV_EVENT_CLICKED, NULL);
}

//--------------------------------------------------------------------------------
//
//--------------------------------------------------------------------------------
static void add_node_to_list(Node *node, lv_obj_t *list) {
  for (auto &n : node->children) {
    if (cell_count++ >= MAX_CELLS) {
      // printf("count: %d\n", cell_count);
      return;
    }

    lv_obj_t * cell = lv_list_add_text(list, n->name.c_str());
    set_styles(cell, n);

    if (n->children.size()) {
      add_node_to_list(n, list);
    }
  }
}

//--------------------------------------------------------------------------------
//
//--------------------------------------------------------------------------------
static void playlist_cb(lv_event_t *e) {
  DBG_ASSERT(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED);

  lv_obj_t * obj = lv_event_get_target_obj(e);
  ui_option.selectPlaylist = lv_dropdown_get_selected(obj);
}

//--------------------------------------------------------------------------------
// Set the pointer to the widget to NULL when its object is deleted
//--------------------------------------------------------------------------------
static void delete_cb(lv_event_t *e) {
  lv_obj_t **obj = (lv_obj_t **)lv_event_get_user_data(e);
  static constexpr lv_obj_t ** const adrs[] = {
    &ui_ScreenAlbumList,
    &album_list,
  };

  for (int i = 0; i < sizeof(adrs) / sizeof(adrs[0]); i++) {
    if (obj == adrs[i]) {
      *obj = NULL;
      DBG_EXEC(printf("deleted: %d\n", i));
      return;
    }
  }
  DBG_EXEC(printf("deleted: 0x%x\n", obj));
}

//--------------------------------------------------------------------------------
// Initialize / Deinitialize widgets
//--------------------------------------------------------------------------------
void ui_ScreenAlbumList_screen_init(void) {
  if (ui_ScreenAlbumList == NULL) {
    ui_ScreenAlbumList = lv_obj_create(NULL);
    lv_obj_set_style_bg_color (ui_ScreenAlbumList, UI_COLOR_BACKGROUND, 0);
    lv_obj_add_event_cb       (ui_ScreenAlbumList, ui_event_ScreenAlbumList, LV_EVENT_GESTURE, NULL);
    lv_obj_add_event_cb       (ui_ScreenAlbumList, ui_event_ScreenAlbumList, LV_EVENT_SCREEN_LOADED, NULL);
    lv_obj_add_event_cb       (ui_ScreenAlbumList, ui_event_ScreenAlbumList, LV_EVENT_SCREEN_UNLOADED, NULL);
    lv_obj_add_event_cb       (ui_ScreenAlbumList, delete_cb, LV_EVENT_DELETE, (void*)&ui_ScreenAlbumList);

#if SHOW_ARROW_BUTTON
    //////////////////// Arrow Icon ////////////////////
    {
      static constexpr lv_style_const_prop_t style_prop_common[] = {
        LV_STYLE_CONST_WIDTH(27),
        LV_STYLE_CONST_HEIGHT(27),
        LV_STYLE_CONST_X(LV_PCT_X(42)),
        LV_STYLE_CONST_Y(LV_PCT_Y(-44)),
        LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
        LV_STYLE_CONST_PROPS_END
      };
      static constexpr lv_style_const_prop_t style_prop_default[] = {
        LV_STYLE_CONST_BG_IMAGE_SRC(&img_menu_right),
        LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
        LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE),
        LV_STYLE_CONST_BORDER_WIDTH(0),
        LV_STYLE_CONST_PAD_TOP(8),
        LV_STYLE_CONST_PAD_RIGHT(0),
        LV_STYLE_CONST_PAD_BOTTOM(0),
        LV_STYLE_CONST_PAD_LEFT(8),
        LV_STYLE_CONST_PROPS_END
      };
      static constexpr lv_style_const_prop_t style_prop_pressed[] = {
        LV_STYLE_CONST_PAD_TOP(10),
        LV_STYLE_CONST_PAD_LEFT(10),
        LV_STYLE_CONST_PROPS_END
      };
      static constexpr lv_style_const_prop_t style_prop_checked[] = {
        LV_STYLE_CONST_BG_IMAGE_SRC(&img_menu_right),
        LV_STYLE_CONST_BG_COLOR(UI_COLOR_BACKGROUND),
        LV_STYLE_CONST_PROPS_END
      };
      static LV_STYLE_CONST_INIT(style_common,  (void*)style_prop_common );
      static LV_STYLE_CONST_INIT(style_default, (void*)style_prop_default);
      static LV_STYLE_CONST_INIT(style_pressed, (void*)style_prop_pressed);
      static LV_STYLE_CONST_INIT(style_checked, (void*)style_prop_checked);

      lv_obj_t *obj = lv_checkbox_create(ui_ScreenAlbumList);
      lv_checkbox_set_text_static(obj, "");
      lv_obj_add_style    (obj, &style_common,  (uint32_t)LV_PART_MAIN      | (uint32_t)LV_STATE_DEFAULT);
      lv_obj_add_style    (obj, &style_default, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_DEFAULT);
      lv_obj_add_style    (obj, &style_pressed, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_PRESSED);
      lv_obj_add_style    (obj, &style_checked, (uint32_t)LV_PART_INDICATOR | (uint32_t)LV_STATE_CHECKED);
      lv_obj_add_event_cb (obj, ui_event_ScreenAlbumList, LV_EVENT_CLICKED, NULL);
    }
#endif

    //////////////////// Title Label ////////////////////
    lv_obj_t *obj = lv_label_create(ui_ScreenAlbumList);
    lv_obj_set_pos(obj, LV_PCT_X(5), LV_PCT_Y(4));
    lv_label_set_text_static(obj, "Album list");

    //////////////////// Dropdown List ////////////////////
    obj = lv_dropdown_create(ui_ScreenAlbumList);
    lv_obj_set_pos          (obj, LV_PCT_X(5), LV_PCT_Y(11));
    lv_obj_set_size         (obj, OPTIONS_WIDTH, LV_SIZE_CONTENT);
    lv_obj_add_event_cb     (obj, playlist_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_dropdown_set_options (obj, "All");
    lv_dropdown_set_selected(obj, ui_option.selectPlaylist);

    //////////////////// List Container ////////////////////
    static constexpr lv_style_const_prop_t style_prop_album[] = {
      LV_STYLE_CONST_X(LV_PCT_X(5)),
      LV_STYLE_CONST_Y(LV_PCT_Y(26)),
      LV_STYLE_CONST_WIDTH(SCREEN_WIDTH - LV_PCT_X(10)),
      LV_STYLE_CONST_HEIGHT(ALBUM_CELL_HEIGHT * ALBUM_CELL_COUNTS - 4),
      LV_STYLE_CONST_PROPS_END
    };
    static LV_STYLE_CONST_INIT(style_album, (void*)style_prop_album);

    album_list = lv_list_create(ui_ScreenAlbumList);
    lv_obj_add_style    (album_list, &style_album, 0);
    lv_obj_add_event_cb (album_list, delete_cb, LV_EVENT_DELETE, (void*)&album_list);
  }
}

void ui_ScreenAlbumList_screen_deinit(void) {
  if (ui_ScreenAlbumList) {
    // Clear playlist before creating a new list
    CYD_MP3Player *player = ui_get_player();
    player->ClearAudioFiles();

    lv_obj_delete_async(ui_ScreenAlbumList);
  }
}

//--------------------------------------------------------------------------------
// Create selectable playlist
//--------------------------------------------------------------------------------
void ui_ScreenAlbumList_create_list(const char *root_dir) {
  // Clear album list before creating a new list
  reset_cell_count(); // Defined in list.cpp

  // Create the album list from playlist
  CYD_MP3Player *player = ui_get_player();
  if (player->m_tree) {
    add_node_to_list(player->m_tree, album_list);
  }
}